# RAGAS 구현하기
기존 RAG 과정에 ReverseHyDE를 도입 → 어느 정도의 성능 향상이 있는지 RAGAS 평가지표를 기준으로 확인해보고자 했다.

In [1]:
!pip install -U -q langchain langchain-openai
!pip install -U -q langchain-community langchain-core
!pip install -U langchain-text-splitters

Requirement already satisfied: langchain-text-splitters in /usr/local/lib/python3.12/dist-packages (1.1.1)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.13 in /usr/local/lib/python3.12/dist-packages (from langchain-text-splitters) (1.2.19)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (0.7.16)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (26.0)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (2.12.3)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (0.14.1)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (3.0.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (3.11.7)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (2.32.5)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (3.6.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (0.4.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (3.4.5)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (2.5.0)

In [4]:
import os

In [5]:
# 2. 구글 드라이브 마운트
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [6]:
from google.colab import userdata
os.environ['OPENAI_API_KEY'] = userdata.get('OPENAI_KEY')

In [6]:
!pip install -q pypdf pdf2image docx2txt pdfminer unstructured #의존성 모듈을 설치합니다

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 32.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 39.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.1/68.1 kB 3.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 333.7/333.7 kB 19.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 55.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.7/107.7 kB 7.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 30.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 453.8/453.8 kB 24.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.6/155.6 kB 10.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.8/167.8 kB 10.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 59.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 220.2/220.2 kB 13.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.0/88.0 kB 4.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 56.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 80.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.6/114.6 kB 7.3 MB/s eta 0:00:00
  Building wheel for pdfminer (setup.py) ... done
  Building wheel for langdetect (setup.py) ... done

In [9]:
from langchain_openai import ChatOpenAI

In [10]:
# 8. OpenAI LLM 설정 (GPT-4o 또는 GPT-3.5-turbo 등)
llm_openai = ChatOpenAI(model="gpt-4o-mini", temperature=0.7)

## 토크나이저 정의 및 PDF 문서 로드

In [9]:
!pip install tiktoken

Requirement already satisfied: tiktoken in /usr/local/lib/python3.12/dist-packages (0.12.0)
Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.12/dist-packages (from tiktoken) (2025.11.3)
Requirement already satisfied: requests>=2.26.0 in /usr/local/lib/python3.12/dist-packages (from tiktoken) (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->tiktoken) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->tiktoken) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->tiktoken) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->tiktoken) (2026.2.25)

In [11]:
import tiktoken

In [12]:
# 5. 토크나이저 설정
tokenizer = tiktoken.get_encoding("cl100k_base")   # GPT-4, GPT-3.5-turbo 모델들이 사용하는 인코딩 방식

def tiktoken_len(text):
    tokens = tokenizer.encode(text)
    return len(tokens)

In [12]:
!pip install chromadb

Collecting chromadb
  Downloading chromadb-1.5.5-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.2 kB)
Collecting build>=1.0.3 (from chromadb)
  Downloading build-1.4.0-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: pydantic>=2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (2.12.3)
Requirement already satisfied: pydantic-settings>=2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (2.13.1)
Collecting pybase64>=1.4.1 (from chromadb)
  Downloading pybase64-1.4.3-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl.metadata (8.7 kB)
Requirement already satisfied: uvicorn>=0.18.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.41.0)
Requirement already satisfied: numpy>=1.22.5 in /usr/local/lib/python3.12/dist-packages (from chromadb) (2.0.2)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (4.15.0)
Collecting onnxruntime>=1.14.1 (from chromadb)
  Downloading onnxruntime-1.24.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.2 kB)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.38.0)
Collecting opentelemetry-exporter-otlp-proto-grpc>=1.2.0 (from chromadb)
  Downloading opentelemetry_exporter_otlp_proto_grpc-1.40.0-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.38.0)
Requirement already satisfied: tokenizers>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.22.2)
Collecting pypika>=0.48.9 (from chromadb)
  Downloading pypika-0.51.1-py2.py3-none-any.whl.metadata (51 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.0/52.0 kB 1.9 MB/s eta 0:00:00
Requirement already satisfied: tqdm>=4.65.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (4.67.3)
Requirement already satisfied: overrides>=7.3.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (7.7.0)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.12/dist-packages (from chromadb) (6.5.2)
Requirement already satisfied: grpcio>=1.58.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.78.0)
Collecting bcrypt>=4.0.1 (from chromadb)
  Downloading bcrypt-5.0.0-cp39-abi3-manylinux_2_34_x86_64.whl.metadata (10 kB)
Requirement already satisfied: typer>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.24.1)
Collecting kubernetes>=28.1.0 (from chromadb)
  Downloading kubernetes-35.0.0-py2.py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: tenacity>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from chromadb) (9.1.4)
Requirement already satisfied: pyyaml>=6.0.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (6.0.3)
Requirement already satisfied: mmh3>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (5.2.1)
Requirement already satisfied: orjson>=3.9.12 in /usr/local/lib/python3.12/dist-packages (from chromadb) (3.11.7)
Requirement already satisfied: httpx>=0.27.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.28.1)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (13.9.4)
Requirement already satisfied: jsonschema>=4.19.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (4.26.0)
Requirement already satisfied: packaging>=24.0 in /usr/local/lib/python3.12/dist-packages (from build>=1.0.3->chromadb) (26.0)
Collecting pyproject_hooks (from build>=1.0.3->chromadb)
  Downloading pyproject_hooks-1.2.0-py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.27.0->chromadb) (0.16.0)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (0.30.0)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (1.17.0)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.9.0.post0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (1.9.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.32.5)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.0.0)
Requirement already satisfied: urllib3!=2.6.0,>=1.24.2 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.5.0)
Collecting durationpy>=0.7 (from kubernetes>=28.1.0->chromadb)
  Downloading durationpy-0.10-py3-none-any.whl.metadata (340 bytes)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb) (25.12.19)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb) (5.29.6)
Requirement already satisfied: sympy in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb) (1.14.0)
Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-api>=1.2.0->chromadb) (8.7.1)
Requirement already satisfied: googleapis-common-protos~=1.57 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.73.0)
Collecting opentelemetry-exporter-otlp-proto-common==1.40.0 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb)
  Downloading opentelemetry_exporter_otlp_proto_common-1.40.0-py3-none-any.whl.metadata (1.9 kB)
Collecting opentelemetry-proto==1.40.0 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb)
  Downloading opentelemetry_proto-1.40.0-py3-none-any.whl.metadata (2.4 kB)
Collecting opentelemetry-sdk>=1.2.0 (from chromadb)
  Downloading opentelemetry_sdk-1.40.0-py3-none-any.whl.metadata (1.6 kB)
Collecting opentelemetry-api>=1.2.0 (from chromadb)
  Downloading opentelemetry_api-1.40.0-py3-none-any.whl.metadata (1.5 kB)
Collecting opentelemetry-semantic-conventions==0.61b0 (from opentelemetry-sdk>=1.2.0->chromadb)
  Downloading opentelemetry_semantic_conventions-0.61b0-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings>=2.0->chromadb) (1.2.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb) (2.19.2)
Requirement already satisfied: huggingface-hub<2.0,>=0.16.4 in /usr/local/lib/python3.12/dist-packages (from tokenizers>=0.13.2->chromadb) (1.6.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (0.0.4)
Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.7.1)
Requirement already satisfied: uvloop>=0.15.1 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.22.1)
Requirement already satisfied: watchfiles>=0.20 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (1.1.1)
Requirement already satisfied: websockets>=10.4 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (15.0.1)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (1.4.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api>=1.2.0->chromadb) (3.23.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->chromadb) (0.1.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kubernetes>=28.1.0->chromadb) (3.4.5)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib->kubernetes>=28.1.0->chromadb) (3.3.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy->onnxruntime>=1.14.1->chromadb) (1.3.0)
Downloading chromadb-1.5.5-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (21.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.6/21.6 MB 43.0 MB/s eta 0:00:00
Downloading bcrypt-5.0.0-cp39-abi3-manylinux_2_34_x86_64.whl (278 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 278.2/278.2 kB 10.6 MB/s eta 0:00:00
Downloading build-1.4.0-py3-none-any.whl (24 kB)
Downloading kubernetes-35.0.0-py2.py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 23.2 MB/s eta 0:00:00
Downloading onnxruntime-1.24.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (17.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.2/17.2 MB 29.3 MB/s eta 0:00:00
Downloading opentelemetry_exporter_otlp_proto_grpc-1.40.0-py3-none-any.whl (20 kB)
Downloading opentelemetry_exporter_otlp_proto_common-1.40.0-py3-none-any.whl (18 kB)
Downloading opentelemetry_proto-1.40.0-py3-none-any.whl (72 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.1/72.1 kB 3.1 MB/s eta 0:00:00
Downloading opentelemetry_sdk-1.40.0-py3-none-any.whl (141 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 142.0/142.0 kB 7.1 MB/s eta 0:00:00
Downloading opentelemetry_api-1.40.0-py3-none-any.whl (68 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.7/68.7 kB 2.4 MB/s eta 0:00:00
Downloading opentelemetry_semantic_conventions-0.61b0-py3-none-any.whl (231 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 231.6/231.6 kB 10.4 MB/s eta 0:00:00
Downloading pybase64-1.4.3-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.6/71.6 kB 2.0 MB/s eta 0:00:00
Downloading pypika-0.51.1-py2.py3-none-any.whl (60 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 2.5 MB/s eta 0:00:00
Downloading durationpy-0.10-py3-none-any.whl (3.9 kB)
Downloading pyproject_hooks-1.2.0-py3-none-any.whl (10 kB)
Installing collected packages: pypika, durationpy, pyproject_hooks, pybase64, opentelemetry-proto, bcrypt, opentelemetry-exporter-otlp-proto-common, opentelemetry-api, onnxruntime, build, opentelemetry-semantic-conventions, kubernetes, opentelemetry-sdk, opentelemetry-exporter-otlp-proto-grpc, chromadb
  Attempting uninstall: opentelemetry-proto
    Found existing installation: opentelemetry-proto 1.38.0
    Uninstalling opentelemetry-proto-1.38.0:
      Successfully uninstalled opentelemetry-proto-1.38.0
  Attempting uninstall: opentelemetry-exporter-otlp-proto-common
    Found existing installation: opentelemetry-exporter-otlp-proto-common 1.38.0
    Uninstalling opentelemetry-exporter-otlp-proto-common-1.38.0:
      Successfully uninstalled opentelemetry-exporter-otlp-proto-common-1.38.0
  Attempting uninstall: opentelemetry-api
    Found existing installation: opentelemetry-api 1.38.0
    Uninstalling opentelemetry-api-1.38.0:
      Successfully uninstalled opentelemetry-api-1.38.0
  Attempting uninstall: opentelemetry-semantic-conventions
    Found existing installation: opentelemetry-semantic-conventions 0.59b0
    Uninstalling opentelemetry-semantic-conventions-0.59b0:
      Successfully uninstalled opentelemetry-semantic-conventions-0.59b0
  Attempting uninstall: opentelemetry-sdk
    Found existing installation: opentelemetry-sdk 1.38.0
    Uninstalling opentelemetry-sdk-1.38.0:
      Successfully uninstalled opentelemetry-sdk-1.38.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opentelemetry-exporter-gcp-logging 1.11.0a0 requires opentelemetry-sdk<1.39.0,>=1.35.0, but you have opentelemetry-sdk 1.40.0 which is incompatible.
opentelemetry-exporter-otlp-proto-http 1.38.0 requires opentelemetry-exporter-otlp-proto-common==1.38.0, but you have opentelemetry-exporter-otlp-proto-common 1.40.0 which is incompatible.
opentelemetry-exporter-otlp-proto-http 1.38.0 requires opentelemetry-proto==1.38.0, but you have opentelemetry-proto 1.40.0 which is incompatible.
opentelemetry-exporter-otlp-proto-http 1.38.0 requires opentelemetry-sdk~=1.38.0, but you have opentelemetry-sdk 1.40.0 which is incompatible.
google-adk 1.26.0 requires opentelemetry-api<1.39.0,>=1.36.0, but you have opentelemetry-api 1.40.0 which is incompatible.
google-adk 1.26.0 requires opentelemetry-sdk<1.39.0,>=1.36.0, but you have opentelemetry-sdk 1.40.0 which is incompatible.
Successfully installed bcrypt-5.0.0 build-1.4.0 chromadb-1.5.5 durationpy-0.10 kubernetes-35.0.0 onnxruntime-1.24.4 opentelemetry-api-1.40.0 opentelemetry-exporter-otlp-proto-common-1.40.0 opentelemetry-exporter-otlp-proto-grpc-1.40.0 opentelemetry-proto-1.40.0 opentelemetry-sdk-1.40.0 opentelemetry-semantic-conventions-0.61b0 pybase64-1.4.3 pypika-0.51.1 pyproject_hooks-1.2.0

In [13]:
!pip install langchain-chroma

Collecting langchain-chroma
  Downloading langchain_chroma-1.1.0-py3-none-any.whl.metadata (1.9 kB)
Requirement already satisfied: chromadb<2.0.0,>=1.3.5 in /usr/local/lib/python3.12/dist-packages (from langchain-chroma) (1.5.5)
Requirement already satisfied: langchain-core<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from langchain-chroma) (1.2.19)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from langchain-chroma) (2.0.2)
Requirement already satisfied: build>=1.0.3 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.4.0)
Requirement already satisfied: pydantic>=2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (2.12.3)
Requirement already satisfied: pydantic-settings>=2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (2.13.1)
Requirement already satisfied: pybase64>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.4.3)
Requirement already satisfied: uvicorn>=0.18.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.41.0)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (4.15.0)
Requirement already satisfied: onnxruntime>=1.14.1 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.24.4)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.40.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.40.0)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.40.0)
Requirement already satisfied: tokenizers>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.22.2)
Requirement already satisfied: pypika>=0.48.9 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.51.1)
Requirement already satisfied: tqdm>=4.65.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (4.67.3)
Requirement already satisfied: overrides>=7.3.1 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (7.7.0)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (6.5.2)
Requirement already satisfied: grpcio>=1.58.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.78.0)
Requirement already satisfied: bcrypt>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (5.0.0)
Requirement already satisfied: typer>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.24.1)
Requirement already satisfied: kubernetes>=28.1.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (35.0.0)
Requirement already satisfied: tenacity>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (9.1.4)
Requirement already satisfied: pyyaml>=6.0.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (6.0.3)
Requirement already satisfied: mmh3>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (5.2.1)
Requirement already satisfied: orjson>=3.9.12 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (3.11.7)
Requirement already satisfied: httpx>=0.27.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.28.1)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (13.9.4)
Requirement already satisfied: jsonschema>=4.19.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (4.26.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.1.3->langchain-chroma) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.1.3->langchain-chroma) (0.7.16)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.1.3->langchain-chroma) (26.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.1.3->langchain-chroma) (0.14.1)
Requirement already satisfied: pyproject_hooks in /usr/local/lib/python3.12/dist-packages (from build>=1.0.3->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.2.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.27.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.1.3->langchain-chroma) (3.0.0)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.30.0)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.17.0)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (2.9.0.post0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.9.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (2.32.5)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (2.0.0)
Requirement already satisfied: urllib3!=2.6.0,>=1.24.2 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (2.5.0)
Requirement already satisfied: durationpy>=0.7 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.10)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.1.3->langchain-chroma) (1.0.0)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.1.3->langchain-chroma) (3.6.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.1.3->langchain-chroma) (0.25.0)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb<2.0.0,>=1.3.5->langchain-chroma) (25.12.19)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb<2.0.0,>=1.3.5->langchain-chroma) (5.29.6)
Requirement already satisfied: sympy in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.14.0)
Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-api>=1.2.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (8.7.1)
Requirement already satisfied: googleapis-common-protos~=1.57 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.73.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.40.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.40.0)
Requirement already satisfied: opentelemetry-proto==1.40.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.40.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.61b0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk>=1.2.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.61b0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings>=2.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.2.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (2.19.2)
Requirement already satisfied: huggingface-hub<2.0,>=0.16.4 in /usr/local/lib/python3.12/dist-packages (from tokenizers>=0.13.2->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.6.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.0.4)
Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.7.1)
Requirement already satisfied: uvloop>=0.15.1 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.22.1)
Requirement already satisfied: watchfiles>=0.20 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.1.1)
Requirement already satisfied: websockets>=10.4 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb<2.0.0,>=1.3.5->langchain-chroma) (15.0.1)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb<2.0.0,>=1.3.5->langchain-chroma) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb<2.0.0,>=1.3.5->langchain-chroma) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.4.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api>=1.2.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (3.23.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.1.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (3.4.5)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib->kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (3.3.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy->onnxruntime>=1.14.1->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.3.0)
Downloading langchain_chroma-1.1.0-py3-none-any.whl (12 kB)
Installing collected packages: langchain-chroma
Successfully installed langchain-chroma-1.1.0

In [13]:
from langchain_chroma import Chroma

In [14]:
from langchain_community.document_loaders import PyPDFLoader

In [15]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

In [4]:
!pip install --upgrade opentelemetry-api
!pip install --upgrade opentelemetry-sdk

Requirement already satisfied: opentelemetry-api in /usr/local/lib/python3.12/dist-packages (1.40.0)
Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-api) (8.7.1)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-api) (4.15.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api) (3.23.0)
Requirement already satisfied: opentelemetry-sdk in /usr/local/lib/python3.12/dist-packages (1.40.0)
Requirement already satisfied: opentelemetry-api==1.40.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk) (1.40.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.61b0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk) (0.61b0)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk) (4.15.0)
Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-api==1.40.0->opentelemetry-sdk) (8.7.1)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api==1.40.0->opentelemetry-sdk) (3.23.0)

## Text Splitting

In [16]:
# 위에서 사용했던 코드입니다
loader = PyPDFLoader("/content/drive/MyDrive/Demian.pdf")
pages = loader.load_and_split()

text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=50, length_function = tiktoken_len)
texts = text_splitter.split_documents(pages)

In [17]:
tiktoken_length = []
for doc in texts:
    # chunk(Document 객체)가 아니라 내부의 텍스트(.page_content)를 전달
    tiktoken_length.append(tiktoken_len(doc.page_content))

print(f"생성된 조각 개수: {len(texts)}")
print(f"조각별 토큰 길이: {tiktoken_length}")

생성된 조각 개수: 182
조각별 토큰 길이: [16, 36, 327, 426, 303, 414, 416, 427, 418, 405, 388, 399, 423, 409, 411, 396, 452, 425, 433, 432, 431, 423, 425, 387, 427, 283, 318, 418, 399, 425, 419, 440, 399, 403, 421, 407, 395, 388, 399, 400, 400, 397, 417, 359, 400, 400, 406, 448, 282, 301, 414, 422, 442, 421, 411, 415, 414, 396, 427, 440, 414, 362, 418, 439, 437, 389, 422, 383, 393, 411, 417, 332, 313, 422, 402, 432, 415, 429, 449, 418, 424, 441, 416, 411, 403, 433, 418, 414, 427, 444, 375, 413, 410, 431, 441, 431, 268, 315, 416, 415, 399, 423, 456, 412, 452, 411, 435, 396, 406, 386, 419, 438, 421, 401, 435, 429, 395, 323, 432, 423, 442, 386, 396, 416, 391, 426, 427, 414, 419, 401, 355, 424, 397, 385, 389, 424, 418, 421, 447, 422, 421, 153, 312, 421, 391, 402, 376, 407, 400, 398, 423, 428, 415, 411, 401, 410, 401, 424, 402, 387, 409, 387, 429, 419, 411, 403, 420, 403, 339, 383, 293, 326, 421, 365, 389, 400, 378, 405, 431, 408, 407, 230]

### 텍스트 임베딩

In [18]:
import openai

In [19]:
client = openai.OpenAI()

In [20]:
for model in client.models.list():
    if "embedding" in model.id:
        print(model.id)

text-embedding-3-small
text-embedding-3-large
text-embedding-ada-002

In [21]:
from langchain_openai import OpenAIEmbeddings

## 벡터 데이터베이스(Vector DB) 구축

In [22]:
embedding_model = OpenAIEmbeddings(model="text-embedding-3-small")

In [23]:
db = Chroma.from_documents(texts, embedding_model)

In [24]:
query = "how Demian look like?"
docs = db.similarity_search(query)

In [25]:
print(docs[1].page_content)

DEMIAN
Why had it only just dawned on me I It wu Demian'•
face.
Later I often comP9Xed the face on the paper with
Demian's features as l remembered them. They were
certainly, though similar, not the same. But beyond all
doubt, it was Demian.
Once one evening in early summer the sun was slant­
ing red through my window that faced westward. Inside
the room it was dusk It occurred to me to attach the
picture of Beatrice (or Demian) to the window bar and
watch the effect as the sun shone through. The outlines
of the face were blurred but the eyes, edged with pink.,
the brightness of the forehead and the energetic red
mouth glowed excitingly from the surface. For a long
time I sat opposite it even after the picture had faded
out. And gradually a feeling came over me that it was
neither Beatrice nor Demian but myself. Not that the
picture was like me-I did not feel it should be-but
the face somehow expressed my life, it was my inner self,
my fate or my daimon. That was how my friend would
look if and when I ever found him again. The woman I
loved, if ever I had a lover, would look like that. It was
the pattern of my life and death; it expressed the tone
and rhythm of my fate.
During those weeks I had embarked on some reading
which made a deeper impression on me than anything I
had read before. Even in later life I have seldom been
so completely absorbed by any books, perhaps not even
excepting Nietzsche's. It was a volume of Novalis• con-
• T,anslalor, not.. The novel D,mian was fint publiahed under the
paeuc:IO!lym Emil Sinclair, the name or a friend or the poet Novalil
whom Hme 10 much admired, ·
91
Downloaded from https://www.holybooks.com

## Reverse HyDE 구현

In [26]:
# [핵심 로직] Reverse HyDE 구현 예시
from langchain_core.documents import Document

# 1. 데이터를 담을 빈 리스트 생성
reverse_hyde_texts = []

# 2. 진행 상황 출력
print(f"총 {len(texts)}개의 문서 조각에서 예상 질문 생성을 시작합니다...")

# 3. 루프 실행
for i, doc in enumerate(texts):
    # 진행 상황 출력
    print(f"[{i+1}/{len(texts)}] 번째 조각 처리 중...")

    # LLM에게 예상 질문 생성 요청 (문구는 필요에 따라 조정 가능)
    # response.content는 LLM이 생성한 답변 텍스트입니다.
    response = llm_openai.invoke(f"다음 내용을 읽고, 이 내용이 정답이 될 수 있는 질문 3개만 써줘:\n\n{doc.page_content}")

    # 원본 내용 + 예상 질문 합치기 (이것이 Reverse HyDE의 핵심입니다)
    enhanced_content = f"예상 질문들:\n{response.content}\n\n원본 내용:\n{doc.page_content}"

    # 새로운 Document 객체 생성 (기존 metadata 유지)
    new_doc = Document(page_content=enhanced_content, metadata=doc.metadata)
    reverse_hyde_texts.append(new_doc)

# 4. 강화된 데이터를 벡터 DB에 저장 (루프가 완전히 끝난 후 실행)
# embedding_model은 이미 정의되어 있다고 가정합니다.
docsearch = Chroma.from_documents(
    documents=reverse_hyde_texts,
    embedding=embedding_model,
    collection_name="reverse_hyde_collection" # 선택 사항: 컬렉션 이름 지정
)

print(f"총 {len(reverse_hyde_texts)}개의 강화된 문서로 Vector Database 구축이 완료되었습니다!")

총 182개의 문서 조각에서 예상 질문 생성을 시작합니다...
[1/182] 번째 조각 처리 중...
[2/182] 번째 조각 처리 중...
[3/182] 번째 조각 처리 중...
[4/182] 번째 조각 처리 중...
[5/182] 번째 조각 처리 중...
[6/182] 번째 조각 처리 중...
[7/182] 번째 조각 처리 중...
[8/182] 번째 조각 처리 중...
[9/182] 번째 조각 처리 중...
[10/182] 번째 조각 처리 중...
[11/182] 번째 조각 처리 중...
[12/182] 번째 조각 처리 중...
[13/182] 번째 조각 처리 중...
[14/182] 번째 조각 처리 중...
[15/182] 번째 조각 처리 중...
[16/182] 번째 조각 처리 중...
[17/182] 번째 조각 처리 중...
[18/182] 번째 조각 처리 중...
[19/182] 번째 조각 처리 중...
[20/182] 번째 조각 처리 중...
[21/182] 번째 조각 처리 중...
[22/182] 번째 조각 처리 중...
[23/182] 번째 조각 처리 중...
[24/182] 번째 조각 처리 중...
[25/182] 번째 조각 처리 중...
[26/182] 번째 조각 처리 중...
[27/182] 번째 조각 처리 중...
[28/182] 번째 조각 처리 중...
[29/182] 번째 조각 처리 중...
[30/182] 번째 조각 처리 중...
[31/182] 번째 조각 처리 중...
[32/182] 번째 조각 처리 중...
[33/182] 번째 조각 처리 중...
[34/182] 번째 조각 처리 중...
[35/182] 번째 조각 처리 중...
[36/182] 번째 조각 처리 중...
[37/182] 번째 조각 처리 중...
[38/182] 번째 조각 처리 중...
[39/182] 번째 조각 처리 중...
[40/182] 번째 조각 처리 중...
[41/182] 번째 조각 처리 중...
[42/182] 번째 조각 처리 중...
[43/182] 번째 조각 처리 중...
[44/182] 번째 조각 처리 중...
[45/182] 번째 조각 처리 중...
[46/182] 번째 조각 처리 중...
[47/182] 번째 조각 처리 중...
[48/182] 번째 조각 처리 중...
[49/182] 번째 조각 처리 중...
[50/182] 번째 조각 처리 중...
[51/182] 번째 조각 처리 중...
[52/182] 번째 조각 처리 중...
[53/182] 번째 조각 처리 중...
[54/182] 번째 조각 처리 중...
[55/182] 번째 조각 처리 중...
[56/182] 번째 조각 처리 중...
[57/182] 번째 조각 처리 중...
[58/182] 번째 조각 처리 중...
[59/182] 번째 조각 처리 중...
[60/182] 번째 조각 처리 중...
[61/182] 번째 조각 처리 중...
[62/182] 번째 조각 처리 중...
[63/182] 번째 조각 처리 중...
[64/182] 번째 조각 처리 중...
[65/182] 번째 조각 처리 중...
[66/182] 번째 조각 처리 중...
[67/182] 번째 조각 처리 중...
[68/182] 번째 조각 처리 중...
[69/182] 번째 조각 처리 중...
[70/182] 번째 조각 처리 중...
[71/182] 번째 조각 처리 중...
[72/182] 번째 조각 처리 중...
[73/182] 번째 조각 처리 중...
[74/182] 번째 조각 처리 중...
[75/182] 번째 조각 처리 중...
[76/182] 번째 조각 처리 중...
[77/182] 번째 조각 처리 중...
[78/182] 번째 조각 처리 중...
[79/182] 번째 조각 처리 중...
[80/182] 번째 조각 처리 중...
[81/182] 번째 조각 처리 중...
[82/182] 번째 조각 처리 중...
[83/182] 번째 조각 처리 중...
[84/182] 번째 조각 처리 중...
[85/182] 번째 조각 처리 중...
[86/182] 번째 조각 처리 중...
[87/182] 번째 조각 처리 중...
[88/182] 번째 조각 처리 중...
[89/182] 번째 조각 처리 중...
[90/182] 번째 조각 처리 중...
[91/182] 번째 조각 처리 중...
[92/182] 번째 조각 처리 중...
[93/182] 번째 조각 처리 중...
[94/182] 번째 조각 처리 중...
[95/182] 번째 조각 처리 중...
[96/182] 번째 조각 처리 중...
[97/182] 번째 조각 처리 중...
[98/182] 번째 조각 처리 중...
[99/182] 번째 조각 처리 중...
[100/182] 번째 조각 처리 중...
[101/182] 번째 조각 처리 중...
[102/182] 번째 조각 처리 중...
[103/182] 번째 조각 처리 중...
[104/182] 번째 조각 처리 중...
[105/182] 번째 조각 처리 중...
[106/182] 번째 조각 처리 중...
[107/182] 번째 조각 처리 중...
[108/182] 번째 조각 처리 중...
[109/182] 번째 조각 처리 중...
[110/182] 번째 조각 처리 중...
[111/182] 번째 조각 처리 중...
[112/182] 번째 조각 처리 중...
[113/182] 번째 조각 처리 중...
[114/182] 번째 조각 처리 중...
[115/182] 번째 조각 처리 중...
[116/182] 번째 조각 처리 중...
[117/182] 번째 조각 처리 중...
[118/182] 번째 조각 처리 중...
[119/182] 번째 조각 처리 중...
[120/182] 번째 조각 처리 중...
[121/182] 번째 조각 처리 중...
[122/182] 번째 조각 처리 중...
[123/182] 번째 조각 처리 중...
[124/182] 번째 조각 처리 중...
[125/182] 번째 조각 처리 중...
[126/182] 번째 조각 처리 중...
[127/182] 번째 조각 처리 중...
[128/182] 번째 조각 처리 중...
[129/182] 번째 조각 처리 중...
[130/182] 번째 조각 처리 중...
[131/182] 번째 조각 처리 중...
[132/182] 번째 조각 처리 중...
[133/182] 번째 조각 처리 중...
[134/182] 번째 조각 처리 중...
[135/182] 번째 조각 처리 중...
[136/182] 번째 조각 처리 중...
[137/182] 번째 조각 처리 중...
[138/182] 번째 조각 처리 중...
[139/182] 번째 조각 처리 중...
[140/182] 번째 조각 처리 중...
[141/182] 번째 조각 처리 중...
[142/182] 번째 조각 처리 중...
[143/182] 번째 조각 처리 중...
[144/182] 번째 조각 처리 중...
[145/182] 번째 조각 처리 중...
[146/182] 번째 조각 처리 중...
[147/182] 번째 조각 처리 중...
[148/182] 번째 조각 처리 중...
[149/182] 번째 조각 처리 중...
[150/182] 번째 조각 처리 중...
[151/182] 번째 조각 처리 중...
[152/182] 번째 조각 처리 중...
[153/182] 번째 조각 처리 중...
[154/182] 번째 조각 처리 중...
[155/182] 번째 조각 처리 중...
[156/182] 번째 조각 처리 중...
[157/182] 번째 조각 처리 중...
[158/182] 번째 조각 처리 중...
[159/182] 번째 조각 처리 중...
[160/182] 번째 조각 처리 중...
[161/182] 번째 조각 처리 중...
[162/182] 번째 조각 처리 중...
[163/182] 번째 조각 처리 중...
[164/182] 번째 조각 처리 중...
[165/182] 번째 조각 처리 중...
[166/182] 번째 조각 처리 중...
[167/182] 번째 조각 처리 중...
[168/182] 번째 조각 처리 중...
[169/182] 번째 조각 처리 중...
[170/182] 번째 조각 처리 중...
[171/182] 번째 조각 처리 중...
[172/182] 번째 조각 처리 중...
[173/182] 번째 조각 처리 중...
[174/182] 번째 조각 처리 중...
[175/182] 번째 조각 처리 중...
[176/182] 번째 조각 처리 중...
[177/182] 번째 조각 처리 중...
[178/182] 번째 조각 처리 중...
[179/182] 번째 조각 처리 중...
[180/182] 번째 조각 처리 중...
[181/182] 번째 조각 처리 중...
[182/182] 번째 조각 처리 중...
총 182개의 강화된 문서로 Vector Database 구축이 완료되었습니다!

## Retrieval

In [27]:
!pip install -U langchain langchain-classic

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/base_command.py", line 179, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/commands/install.py", line 362, in run
    resolver = self.make_resolver(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/req_command.py", line 177, in make_resolver
    return pip._internal.resolution.resolvelib.resolver.Resolver(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 58, in __init__
    self.factory = Factory(
                   ^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/resolution/resolvelib/factory.py", line 129, in __init__
    for dist in env.iter_installed_distributions(local_only=False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/metadata/base.py", line 664, in <genexpr>
    return (d for d in it if d.canonical_name not in skip)
                       ^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/metadata/base.py", line 612, in iter_all_distributions
    for dist in self._iter_distributions():
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/metadata/importlib/_envs.py", line 176, in _iter_distributions
    yield from finder.find(location)
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/metadata/importlib/_envs.py", line 79, in find
    for dist, info_location in self._find_impl(location):
                               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/metadata/importlib/_envs.py", line 64, in _find_impl
    raw_name = get_dist_name(dist)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/metadata/importlib/_compat.py", line 52, in get_dist_name
    name = cast(Any, dist).name
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 457, in name
    return self.metadata['Name']
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 452, in metadata
    return _adapters.Message(email.message_from_string(text))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/email/__init__.py", line 37, in message_from_string
    return Parser(*args, **kws).parsestr(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/email/parser.py", line 64, in parsestr
    return self.parse(StringIO(text), headersonly=headersonly)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/email/parser.py", line 53, in parse
    feedparser.feed(data)
  File "/usr/lib/python3.12/email/feedparser.py", line 174, in feed
    self._call_parse()
  File "/usr/lib/python3.12/email/feedparser.py", line 178, in _call_parse
    self._parse()
  File "/usr/lib/python3.12/email/feedparser.py", line 462, in _parsegen
    for line in self._input:
                ^^^^^^^^^^^
  File "/usr/lib/python3.12/email/feedparser.py", line 128, in __next__
    line = self.readline()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/email/feedparser.py", line 84, in readline
    line = self._lines.popleft()
           ^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/main.py", line 80, in main
    return command.main(cmd_args)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/base_command.py", line 100, in main
    return self._main(args)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/base_command.py", line 232, in _main
    return run(options, args)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/base_command.py", line 215, in exc_logging_wrapper
    logger.critical("Operation cancelled by user")
  File "/usr/lib/python3.12/logging/__init__.py", line 1586, in critical
    self._log(CRITICAL, msg, args, **kwargs)
  File "/usr/lib/python3.12/logging/__init__.py", line 1684, in _log
    self.handle(record)
  File "/usr/lib/python3.12/logging/__init__.py", line 1700, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.12/logging/__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.12/logging/__init__.py", line 1028, in handle
    self.emit(record)
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/utils/logging.py", line 177, in emit
    self.console.print(renderable, overflow="ignore", crop=False, style=style)
  File "/usr/local/lib/python3.12/dist-packages/pip/_vendor/rich/console.py", line 1674, in print
    renderables = self._collect_renderables(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_vendor/rich/console.py", line 1553, in _collect_renderables
    check_text()
  File "/usr/local/lib/python3.12/dist-packages/pip/_vendor/rich/console.py", line 1531, in check_text
    append(sep_text.join(text))
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_vendor/rich/text.py", line 788, in join
    def iter_text() -> Iterable["Text"]:
                       ~~~~~~~~^^^^^^^^
  File "/usr/lib/python3.12/typing.py", line 395, in inner
    return _caches[func](*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/typing.py", line 1481, in __getitem__
    params = tuple(_type_check(p, msg) for p in params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/typing.py", line 1481, in <genexpr>
    params = tuple(_type_check(p, msg) for p in params)
                   ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/typing.py", line 193, in _type_check
    arg = _type_convert(arg, module=module, allow_special_forms=allow_special_forms)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/typing.py", line 171, in _type_convert
    return ForwardRef(arg, module=module, is_class=allow_special_forms)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/typing.py", line 904, in __init__
    code = compile(arg_to_compile, '<string>', 'eval')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
^C

In [28]:
# from langchain.chains import RetrievalQA에서 바꾼 것
from langchain_classic.chains.retrieval_qa.base import RetrievalQA

In [29]:
from langchain_core.callbacks.streaming_stdout import StreamingStdOutCallbackHandler

llm = ChatOpenAI(
    model="gpt-4o",
    temperature=0.0,
    streaming=True,
    callbacks=[StreamingStdOutCallbackHandler()]
)

In [30]:
qa = RetrievalQA.from_chain_type(
    llm,
    chain_type="stuff",
    retriever=docsearch.as_retriever(
      search_type="mmr",
      search_kwargs={"k": 3, "fetch_k" : 10}),
    return_source_documents=True)

In [31]:
# 10. 질문 실행 및 결과 출력
query = "Who is Sinclair?"
result = qa.invoke(query)

from IPython.display import Markdown, display
display(Markdown(result["result"]))

Sinclair is the protagonist of Hermann Hesse's novel "Demian." The story follows his journey of self-discovery and personal growth, influenced by his interactions with characters like Max Demian and Frau Eva.

Sinclair is the protagonist of Hermann Hesse's novel "Demian." The story follows his journey of self-discovery and personal growth, influenced by his interactions with characters like Max Demian and Frau Eva.

#### RAG를 사용하지 않은 llm 호출

In [ ]:
# llm2 = ChatOpenAI(
#     model="gpt-4o-mini")
# request = llm2.invoke("how demian looks like")
# display(Markdown(request.content))

## RAGAS

In [29]:
!pip install ragas datasets

Collecting ragas
  Downloading ragas-0.4.3-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: numpy<3.0.0,>=1.21.0 in /usr/local/lib/python3.12/dist-packages (from ragas) (2.0.2)
Requirement already satisfied: tiktoken in /usr/local/lib/python3.12/dist-packages (from ragas) (0.12.0)
Requirement already satisfied: pydantic>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ragas) (2.12.3)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from ragas) (1.6.0)
Collecting appdirs (from ragas)
  Downloading appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting diskcache>=5.6.3 (from ragas)
  Downloading diskcache-5.6.3-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from ragas) (0.24.1)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from ragas) (13.9.4)
Requirement already satisfied: openai>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ragas) (2.26.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from ragas) (4.67.3)
Collecting instructor (from ragas)
  Downloading instructor-1.14.5-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: pillow>=10.4.0 in /usr/local/lib/python3.12/dist-packages (from ragas) (11.3.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from ragas) (3.6.1)
Collecting scikit-network (from ragas)
  Downloading scikit_network-0.33.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.5 kB)
Requirement already satisfied: langchain in /usr/local/lib/python3.12/dist-packages (from ragas) (1.2.12)
Requirement already satisfied: langchain-core in /usr/local/lib/python3.12/dist-packages (from ragas) (1.2.19)
Requirement already satisfied: langchain-community in /usr/local/lib/python3.12/dist-packages (from ragas) (0.4.1)
Requirement already satisfied: langchain_openai in /usr/local/lib/python3.12/dist-packages (from ragas) (1.1.11)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.25.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.5)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (1.6.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.13.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (1.4.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.15.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai>=1.0.0->ragas) (4.12.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai>=1.0.0->ragas) (1.9.0)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai>=1.0.0->ragas) (0.13.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai>=1.0.0->ragas) (1.3.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->ragas) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->ragas) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->ragas) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.2.25)
Requirement already satisfied: docstring-parser<1.0,>=0.16 in /usr/local/lib/python3.12/dist-packages (from instructor->ragas) (0.17.0)
Requirement already satisfied: jinja2<4.0.0,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from instructor->ragas) (3.1.6)
Collecting jiter<1,>=0.10.0 (from openai>=1.0.0->ragas)
  Downloading jiter-0.11.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.2 kB)
Requirement already satisfied: tenacity<10.0.0,>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from instructor->ragas) (9.1.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->ragas) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->ragas) (2.19.2)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->ragas) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->ragas) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->ragas) (0.0.4)
Requirement already satisfied: langgraph<1.2.0,>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from langchain->ragas) (1.1.1)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core->ragas) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core->ragas) (0.7.16)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core->ragas) (0.14.1)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community->ragas) (1.0.3)
Requirement already satisfied: SQLAlchemy<3.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community->ragas) (2.0.48)
Requirement already satisfied: dataclasses-json<0.7.0,>=0.6.7 in /usr/local/lib/python3.12/dist-packages (from langchain-community->ragas) (0.6.7)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from langchain-community->ragas) (2.13.1)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community->ragas) (0.4.3)
Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.12/dist-packages (from tiktoken->ragas) (2025.11.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: scipy>=1.7.3 in /usr/local/lib/python3.12/dist-packages (from scikit-network->ragas) (1.16.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community->ragas) (3.26.2)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community->ragas) (0.9.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2<4.0.0,>=3.1.4->instructor->ragas) (3.0.3)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core->ragas) (3.0.0)
Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from langchain-classic<2.0.0,>=1.0.0->langchain-community->ragas) (1.1.1)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.2.0,>=1.1.1->langchain->ragas) (4.0.1)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.8 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.2.0,>=1.1.1->langchain->ragas) (1.0.8)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.2.0,>=1.1.1->langchain->ragas) (0.3.11)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core->ragas) (3.11.7)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core->ragas) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core->ragas) (0.25.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->ragas) (0.1.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community->ragas) (1.2.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from SQLAlchemy<3.0.0,>=1.4.0->langchain-community->ragas) (3.3.2)
Requirement already satisfied: ormsgpack>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from langgraph-checkpoint<5.0.0,>=2.1.0->langgraph<1.2.0,>=1.1.1->langchain->ragas) (1.12.2)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7.0,>=0.6.7->langchain-community->ragas) (1.1.0)
Downloading ragas-0.4.3-py3-none-any.whl (466 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 466.5/466.5 kB 8.5 MB/s eta 0:00:00
Downloading diskcache-5.6.3-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.5/45.5 kB 2.8 MB/s eta 0:00:00
Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Downloading instructor-1.14.5-py3-none-any.whl (177 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 177.4/177.4 kB 12.0 MB/s eta 0:00:00
Downloading scikit_network-0.33.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (8.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 71.9 MB/s eta 0:00:00
Downloading jiter-0.11.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (358 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 358.8/358.8 kB 21.3 MB/s eta 0:00:00
Installing collected packages: appdirs, jiter, diskcache, scikit-network, instructor, ragas
  Attempting uninstall: jiter
    Found existing installation: jiter 0.13.0
    Uninstalling jiter-0.13.0:
      Successfully uninstalled jiter-0.13.0
Successfully installed appdirs-1.4.4 diskcache-5.6.3 instructor-1.14.5 jiter-0.11.1 ragas-0.4.3 scikit-network-0.33.5

In [32]:
from datasets import Dataset
from ragas import evaluate
from ragas.metrics import (
    faithfulness,
    answer_relevancy,
    context_recall,
    context_precision,
)
import pandas as pd

/tmp/ipykernel_6300/2706617862.py:3: DeprecationWarning: Importing faithfulness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import faithfulness
  from ragas.metrics import (
/tmp/ipykernel_6300/2706617862.py:3: DeprecationWarning: Importing answer_relevancy from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import answer_relevancy
  from ragas.metrics import (
/tmp/ipykernel_6300/2706617862.py:3: DeprecationWarning: Importing context_recall from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import context_recall
  from ragas.metrics import (
/tmp/ipykernel_6300/2706617862.py:3: DeprecationWarning: Importing context_precision from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import context_precision
  from ragas.metrics import (

In [33]:
# 1. 평가용 질문 및 정답 정의
eval_questions = [
    "싱클레어는 누구니?",
    "데미안이 싱클레어에게 카인과 아벨에 대해 설명한 내용은 무엇인가요?",
    "크로머는 어떤 방식으로 싱클레어를 협박했나요?"
]

ground_truths = [
    "싱클레어는 소설 '데미안'의 주인공으로, 밝은 세계와 어두운 세계 사이에서 방황하며 자아를 찾아가는 인물입니다.",
    "데미안은 카인의 표식이 악의 상징이 아니라, 남들보다 강하고 지적인 사람들을 구별해주는 고귀한 표식이라고 설명했습니다.",
    "크로머는 싱클레어가 이웃집 과수원에서 사과를 훔쳤다는 거짓 고백을 약점 잡아 돈을 요구하며 그를 괴롭혔습니다."
]

In [34]:
# 2. 결과 수집
results = []
for query in eval_questions:
    # QA 시스템 호출
    response = qa.invoke(query)

    # 답변 추출 (RetrievalQA 결과 구조에 따라 수정)
    answer = response.get("result") or response.get("answer")

    # 검색된 근거 추출 (위에서 만든 docsearch 활용)
    retrieved_docs = docsearch.as_retriever().invoke(query)
    context_list = [doc.page_content for doc in retrieved_docs]

    results.append({
        "question": query,
        "answer": answer,
        "contexts": context_list
    })

싱클레어는 헤르만 헤세의 소설 "데미안"의 주인공입니다. 그는 소설에서 자신의 정체성을 찾고 성장하는 과정을 겪으며, 데미안이라는 인물과의 만남을 통해 내면의 갈등과 자기 발견을 경험하게 됩니다. 싱클레어는 자신의 과거와 현재를 대조하며, 그로 인해 다양한 감정을 느끼고 자기혐오와 같은 복잡한 감정도 겪게 됩니다.죄송하지만, 데미안이 싱클레어에게 카인과 아벨에 대해 설명한 구체적인 내용은 제공된 문맥에서 찾을 수 없습니다.크로머는 싱클레어에게 불가능한 요구를 하며 그를 겁주고 굴욕감을 주는 방식으로 협박했습니다. 그런 다음 점차적으로 요구를 완화하면서 싱클레어가 돈이나 선물로 자신을 구제하도록 만들었습니다. 이번에는 싱클레어의 여동생을 산책에 데리고 나오라는 요청을 했고, 싱클레어는 그러한 요구에 절대 동참하지 않겠다고 결심했습니다. 그러나 크로머가 어떻게 보복할지에 대한 두려움도 느꼈습니다.

In [35]:
# 3. 데이터셋 변환
data = {
    "question": [r["question"] for r in results],
    "answer": [r["answer"] for r in results],
    "contexts": [r["contexts"] for r in results],
    "ground_truth": ground_truths
}
dataset = Dataset.from_dict(data)

In [36]:
# 4. Ragas 평가 실행 (OpenAI API 키가 설정되어 있어야 합니다)
print("Ragas 평가를 시작합니다...")
result = evaluate(
    dataset=dataset,
    metrics=[
        context_precision,
        context_recall,
        faithfulness,
        answer_relevancy,
    ],
)

Ragas 평가를 시작합니다...

Evaluating:   0%|          | 0/12 [00:00<?, ?it/s]

WARNING:ragas.prompt.pydantic_prompt:LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
ERROR:ragas.executor:Exception raised in Job[3]: AttributeError('OpenAIEmbeddings' object has no attribute 'embed_query')
WARNING:ragas.prompt.pydantic_prompt:LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
ERROR:ragas.executor:Exception raised in Job[7]: AttributeError('OpenAIEmbeddings' object has no attribute 'embed_query')
WARNING:ragas.prompt.pydantic_prompt:LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
ERROR:ragas.executor:Exception raised in Job[11]: AttributeError('OpenAIEmbeddings' object has no attribute 'embed_query')

In [37]:
# 5. 결과 확인
print("\n[Ragas 평가 결과]")
print(result)
df = result.to_pandas()
display(df)

[Ragas 평가 결과]
{'context_precision': 0.4444, 'context_recall': 1.0000, 'faithfulness': 0.6111, 'answer_relevancy': nan}

,user_input,retrieved_contexts,response,reference,context_precision,context_recall,faithfulness,answer_relevancy
0,싱클레어는 누구니?,"[예상 질문들:\n1. 이 인물은 자신의 과거와 현재를 어떻게 대조하고 있으며, 그...","싱클레어는 헤르만 헤세의 소설 ""데미안""의 주인공입니다. 그는 소설에서 자신의 정체...","싱클레어는 소설 '데미안'의 주인공으로, 밝은 세계와 어두운 세계 사이에서 방황하며...",0.000000,1.0,0.833333,NaN
1,데미안이 싱클레어에게 카인과 아벨에 대해 설명한 내용은 무엇인가요?,[예상 질문들:\n1. 데미안이 자신의 의지를 통해 다른 사람에게서 원하는 것을 얻...,"죄송하지만, 데미안이 싱클레어에게 카인과 아벨에 대해 설명한 구체적인 내용은 제공된...","데미안은 카인의 표식이 악의 상징이 아니라, 남들보다 강하고 지적인 사람들을 구별해...",0.333333,1.0,0.000000,NaN
2,크로머는 어떤 방식으로 싱클레어를 협박했나요?,"[예상 질문들:\n1. 어떤 요청이 Kromer에 의해 제기되었고, 그 요청에 대한...",크로머는 싱클레어에게 불가능한 요구를 하며 그를 겁주고 굴욕감을 주는 방식으로 협박...,크로머는 싱클레어가 이웃집 과수원에서 사과를 훔쳤다는 거짓 고백을 약점 잡아 돈을 ...,1.000000,1.0,1.000000,NaN

## 정성 평가

In [38]:
# 1. 분석할 질문 리스트 (평가에 사용했던 질문과 동일하게 설정)
analysis_questions = [
    "싱클레어는 누구니?",
    "데미안이 싱클레어에게 카인과 아벨에 대해 설명한 내용은 무엇인가요?",
    "크로머는 어떤 방식으로 싱클레어를 협박했나요?"
]

print("=== Retrieval Analysis (검색 결과 적절성 검토) ===\n")

analysis_results = []

for i, query in enumerate(analysis_questions):
    print(f"🔎 질문 {i+1}: {query}")

    # docsearch(Chroma DB)에서 관련 문서 검색 (k=3)
    # Reverse HyDE로 구축된 DB이므로 '예상 질문'이 포함된 문서를 가져옵니다.
    retrieved_docs = docsearch.as_retriever(search_kwargs={"k": 3}).invoke(query)

    print(f"✅ 검색된 문서 개수: {len(retrieved_docs)}")

    for j, doc in enumerate(retrieved_docs):
        # 검색된 내용의 앞부분 200자만 추출하여 출력
        content_preview = doc.page_content.replace('\n', ' ')[:200]
        source = doc.metadata.get('source', '알 수 없음')
        page = doc.metadata.get('page', '-')

        print(f"   [문서 {j+1}] (출처: {source}, {page}페이지)")
        print(f"   내용 요약: {content_preview}...")
        print("-" * 50)

    print("\n" + "="*80 + "\n")

# (선택 사항) 결과를 표 형태로 정리해서 보고 싶을 때
analysis_data = []
for query in analysis_questions:
    docs = docsearch.as_retriever(search_kwargs={"k": 3}).invoke(query)
    analysis_data.append({
        "Question": query,
        "Top_1_Context": docs[0].page_content[:300] if docs else "검색 결과 없음",
        "Top_2_Context": docs[1].page_content[:300] if len(docs) > 1 else "-",
        "Top_3_Context": docs[2].page_content[:300] if len(docs) > 2 else "-"
    })

df_analysis = pd.DataFrame(analysis_data)
display(df_analysis)

=== Retrieval Analysis (검색 결과 적절성 검토) ===

🔎 질문 1: 싱클레어는 누구니?
✅ 검색된 문서 개수: 3
   [문서 1] (출처: /content/drive/MyDrive/Demian.pdf, 78페이지)
   내용 요약: 예상 질문들: 1. 이 인물은 자신의 과거와 현재를 어떻게 대조하고 있으며, 그로 인해 어떤 감정을 느끼고 있나요? 2. 비트리스가 느끼는 자기혐오의 원인은 무엇이며, 그가 자신을 "아웃캐스트"로 묘사하는 이유는 무엇인가요? 3. 비트리스가 경험한 사랑과 애정의 기억은 현재의 그의 정체성과 어떻게 연결되어 있나요?  원본 내용: BEATRICE  schoo...
--------------------------------------------------
   [문서 2] (출처: /content/drive/MyDrive/Demian.pdf, 88페이지)
   내용 요약: 예상 질문들: 1. 이 그림이 왜 비아트리스의 삶에 큰 영향을 미쳤는가? 2. 비아트리스가 그림을 보고 느낀 감정은 무엇인가? 3. 비아트리스가 꿈에서 그림을 어떻게 인식하게 되었는가?  원본 내용: BEATRICE  This picture haunted my thoughts for a long time and  divided up my life. I ke...
--------------------------------------------------
   [문서 3] (출처: /content/drive/MyDrive/Demian.pdf, 100페이지)
   내용 요약: 예상 질문들: 1. "Abraxas는 어떤 개념을 대표하며, 그것이 의미하는 바는 무엇인가요?" 2. "Demian과의 대화에서 제기된 '신성과 사탄성의 화해'에 대한 아이디어는 어떤 배경을 가지고 있나요?" 3. "주인공이 Beatrice의 형상에 대해 느끼는 변화는 무엇을 나타내고 있나요?"  원본 내용: THE BIRD STRUGGLES OUT OF ...
--------------------------------------------------

================================================================================

🔎 질문 2: 데미안이 싱클레어에게 카인과 아벨에 대해 설명한 내용은 무엇인가요?
✅ 검색된 문서 개수: 3
   [문서 1] (출처: /content/drive/MyDrive/Demian.pdf, 61페이지)
   내용 요약: 예상 질문들: 1. 데미안이 자신의 의지를 통해 다른 사람에게서 원하는 것을 얻기 위해 사용하는 방법은 무엇인가요?    2. 데미안이 언급하지 않은 그의 어머니에 대해 어떤 생각을 하고 있었나요?   3. 화자가 데미안을 흉내 내려고 시도했지만 성공하지 못한 이유는 무엇인가요?  원본 내용: DEMIAN  the thought did not penetra...
--------------------------------------------------
   [문서 2] (출처: /content/drive/MyDrive/Demian.pdf, 70페이지)
   내용 요약: 예상 질문들: 1. "주인공이 '진짜 데미안'이라고 느낀 이유는 무엇인가요?" 2. "데미안이 수업 중에 보였던 변화는 무엇이며, 이것이 주인공에게 어떤 감정을 불러일으켰나요?" 3. "주인공이 데미안의 상태에 대해 느낀 외로움의 원인은 무엇인가요?"  원본 내용: THE THIEF  eyes were fixed on that pale, stone mask...
--------------------------------------------------
   [문서 3] (출처: /content/drive/MyDrive/Demian.pdf, 75페이지)
   내용 요약: 예상 질문들: 1. Sinclair와 Beck이 저녁에 무엇을 하기로 했나요? 2. Sinclair가 술을 마신 후 어떤 감정을 느꼈나요? 3. Beck이 Sinclair에게 어떤 반응을 보였고, 그로 인해 Sinclair의 기분은 어떻게 변했나요?  원본 내용: DEMIAN  .. You don't need to be afraid that I don't ...
--------------------------------------------------

================================================================================

🔎 질문 3: 크로머는 어떤 방식으로 싱클레어를 협박했나요?
✅ 검색된 문서 개수: 3
   [문서 1] (출처: /content/drive/MyDrive/Demian.pdf, 37페이지)
   내용 요약: 예상 질문들: 1. 어떤 요청이 Kromer에 의해 제기되었고, 그 요청에 대한 화자의 반응은 어땠나요? 2. 화자는 Kromer의 요구에 대해 어떤 결심을 하였으며, 그 결심의 배경은 무엇인가요? 3. Max Demian이 등장했을 때 화자는 어떤 감정을 느꼈고, 그 상황에서 어떤 행동을 취했나요?  원본 내용: DEMIAN  was, a ruse and...
--------------------------------------------------
   [문서 2] (출처: /content/drive/MyDrive/Demian.pdf, 107페이지)
   내용 요약: 예상 질문들: 1. 이 인물의 외모에 대한 묘사는 어떤 특징을 강조하고 있나요? 2. 대화 중 두 인물의 관계는 어떻게 발전하고 있나요? 3. 주인공이 상대방에게 특별한 관심을 가지게 된 이유는 무엇인가요?  원본 내용: DEMIAN  I had anticipated. It wu ugly and somewhat wild  looking, interrogat...
--------------------------------------------------
   [문서 3] (출처: /content/drive/MyDrive/Demian.pdf, 58페이지)
   내용 요약: 예상 질문들: 1. 어떤 특정한 종류의 나방에서 수컷이 암컷을 찾기 위해 얼마나 멀리까지 날아갈 수 있는가? 2. 나방 수컷들이 암컷의 냄새를 감지하는 데 사용하는 능력은 무엇과 유사한가? 3. 왜 수컷 나방들이 암컷보다 더 뛰어난 후각을 가지게 되었는가?  원본 내용: THE THIEF  the male fertilizes the female who la...
--------------------------------------------------

================================================================================

,Question,Top_1_Context,Top_2_Context,Top_3_Context
0,싱클레어는 누구니?,"예상 질문들:\n1. 이 인물은 자신의 과거와 현재를 어떻게 대조하고 있으며, 그로...",예상 질문들:\n1. 이 그림이 왜 비아트리스의 삶에 큰 영향을 미쳤는가?\n2. ...,"예상 질문들:\n1. ""Abraxas는 어떤 개념을 대표하며, 그것이 의미하는 바는..."
1,데미안이 싱클레어에게 카인과 아벨에 대해 설명한 내용은 무엇인가요?,예상 질문들:\n1. 데미안이 자신의 의지를 통해 다른 사람에게서 원하는 것을 얻기...,"예상 질문들:\n1. ""주인공이 '진짜 데미안'이라고 느낀 이유는 무엇인가요?""\n...",예상 질문들:\n1. Sinclair와 Beck이 저녁에 무엇을 하기로 했나요?\n...
2,크로머는 어떤 방식으로 싱클레어를 협박했나요?,"예상 질문들:\n1. 어떤 요청이 Kromer에 의해 제기되었고, 그 요청에 대한 ...",예상 질문들:\n1. 이 인물의 외모에 대한 묘사는 어떤 특징을 강조하고 있나요?\...,예상 질문들:\n1. 어떤 특정한 종류의 나방에서 수컷이 암컷을 찾기 위해 얼마나 ...

### 지표 해석
Context Recall : 1

→ 이번에도 100%다. Reverse HyDE가 관련 문서를 찾아오는 능력은 확실히 좋은 것 같다.

Context Precision : 0, 0.3, 1.0

→ 질문과 관련없는 정보가 상위권에 있음을 확인할 수 있다.

Faithfulness : 0.8, 0, 1

→ LLM의 답변이 문서 내용과 관련있다고 볼 수 있다.
<br>
<br>
<br>
ReverseHyDE만 적용한 코드(rag-tutorial_reverse-hyde.ipynb)와 RAGAS를 적용한 코드(ragas-tutorial_reverse-hyde_1.ipynb)를 비교했을 때, RAGAS를 사용한 결과를 보고 실망했다. 계속 모르겠다고 말만 하다니....

코드랑 라이브러리 환경이 다소 달랐지만, 내용은 거의 비슷하다고 생각해서, 비슷한 성능을 가지고 정량 평가만 추가될 거라고 기대했었다. <br>
자세히 살펴보면 아주 조금씩 바뀐 부분이 있긴 한데, 설마 달라지겠나 싶어서 조건을 이전 코드와 똑같이 적용해서 다시 한번 코드를 돌렸다. <br>
<br>
[질문을 뽑아내는 LLM의 조건] <br>
model="gpt-4o-mini", temperature=0.7

[답변을 내는 LLM의 조건] <br>
model="gpt-4o", temperature=0.0

→ 이전 코드와 같은 조건으로 동일하게 적용<br>
<br>

☞ 결론 : 모르겠다고 대답 안한다. 그리고 대답의 내용이 맞는지는 모르나, 질문과 관련된 '대답'은 하고는 있었다.

## 회고
코드 완성하는 데에 시간이 꽤나 오래 걸렸다. 계속된 에러 속에, 제공된 예제 코드와 계속 비교해보면서 내가 뭘 잘못 작성했을까 고민을 참 많이 했던 시간이었다. 그래도 오랜 시간 쏟은 만큼 코드 읽는 버거움이 아주 조금은 사라진 기분이라 나름 뿌듯함도 느낀다.

다만 이 과제에서 핵심이었던 RAGAS를 해석하고 고치는 데에 시간을 더 쓰지 못한 게 아쉽기는 하다. 기존 실습 코드와 마지막으로 작성한 코드도 RAGAS로 비교 분석 결과를 만들고 싶었는데, 좀 아쉽다. 앞으로도 자주 볼 녀석이니까 다음에 다른 과제 제출하면서 써먹어야겠다는 생각이 든다.