# RAGAS 구현하기
기존 RAG 과정에 ReverseHyDE를 도입 → 어느 정도의 성능 향상이 있는지 RAGAS 평가지표를 기준으로 확인해보고자 했다.

In [1]:
!pip install -U -q langchain langchain-openai
!pip install -U -q langchain-community langchain-core
!pip install -U langchain-text-splitters

Requirement already satisfied: langchain-text-splitters in /usr/local/lib/python3.12/dist-packages (1.1.1)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.13 in /usr/local/lib/python3.12/dist-packages (from langchain-text-splitters) (1.2.19)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (0.7.16)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (26.0)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (2.12.3)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (0.14.1)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (3.0.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (3.11.7)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (2.32.5)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (3.6.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (0.4.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (3.4.5)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (2.5.0)

In [2]:
import os

In [3]:
# 2. 구글 드라이브 마운트
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [4]:
from google.colab import userdata
os.environ['OPENAI_API_KEY'] = userdata.get('')

In [5]:
!pip install -q pypdf pdf2image docx2txt pdfminer unstructured #의존성 모듈을 설치합니다

In [6]:
from langchain_openai import ChatOpenAI

In [7]:
# 8. OpenAI LLM 설정 (GPT-4o 또는 GPT-3.5-turbo 등)
llm_openai = ChatOpenAI(model="gpt-4o-mini", temperature=0.7)

## 토크나이저 정의 및 PDF 문서 로드

In [8]:
!pip install tiktoken

Requirement already satisfied: tiktoken in /usr/local/lib/python3.12/dist-packages (0.12.0)
Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.12/dist-packages (from tiktoken) (2025.11.3)
Requirement already satisfied: requests>=2.26.0 in /usr/local/lib/python3.12/dist-packages (from tiktoken) (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->tiktoken) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->tiktoken) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->tiktoken) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->tiktoken) (2026.2.25)

In [9]:
import tiktoken

In [10]:
# 5. 토크나이저 설정
tokenizer = tiktoken.get_encoding("cl100k_base")   # GPT-4, GPT-3.5-turbo 모델들이 사용하는 인코딩 방식

def tiktoken_len(text):
    tokens = tokenizer.encode(text)
    return len(tokens)

In [11]:
!pip install chromadb

Requirement already satisfied: chromadb in /usr/local/lib/python3.12/dist-packages (1.5.5)
Requirement already satisfied: build>=1.0.3 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.4.0)
Requirement already satisfied: pydantic>=2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (2.12.3)
Requirement already satisfied: pydantic-settings>=2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (2.13.1)
Requirement already satisfied: pybase64>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.4.3)
Requirement already satisfied: uvicorn>=0.18.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.41.0)
Requirement already satisfied: numpy>=1.22.5 in /usr/local/lib/python3.12/dist-packages (from chromadb) (2.0.2)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (4.15.0)
Requirement already satisfied: onnxruntime>=1.14.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.24.4)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.40.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.40.0)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.40.0)
Requirement already satisfied: tokenizers>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.22.2)
Requirement already satisfied: pypika>=0.48.9 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.51.1)
Requirement already satisfied: tqdm>=4.65.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (4.67.3)
Requirement already satisfied: overrides>=7.3.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (7.7.0)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.12/dist-packages (from chromadb) (6.5.2)
Requirement already satisfied: grpcio>=1.58.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.78.0)
Requirement already satisfied: bcrypt>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (5.0.0)
Requirement already satisfied: typer>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.24.1)
Requirement already satisfied: kubernetes>=28.1.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (35.0.0)
Requirement already satisfied: tenacity>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from chromadb) (9.1.4)
Requirement already satisfied: pyyaml>=6.0.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (6.0.3)
Requirement already satisfied: mmh3>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (5.2.1)
Requirement already satisfied: orjson>=3.9.12 in /usr/local/lib/python3.12/dist-packages (from chromadb) (3.11.7)
Requirement already satisfied: httpx>=0.27.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.28.1)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (13.9.4)
Requirement already satisfied: jsonschema>=4.19.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (4.26.0)
Requirement already satisfied: packaging>=24.0 in /usr/local/lib/python3.12/dist-packages (from build>=1.0.3->chromadb) (26.0)
Requirement already satisfied: pyproject_hooks in /usr/local/lib/python3.12/dist-packages (from build>=1.0.3->chromadb) (1.2.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.27.0->chromadb) (0.16.0)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (0.30.0)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (1.17.0)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.9.0.post0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (1.9.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.32.5)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.0.0)
Requirement already satisfied: urllib3!=2.6.0,>=1.24.2 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.5.0)
Requirement already satisfied: durationpy>=0.7 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (0.10)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb) (25.12.19)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb) (5.29.6)
Requirement already satisfied: sympy in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb) (1.14.0)
Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-api>=1.2.0->chromadb) (8.7.1)
Requirement already satisfied: googleapis-common-protos~=1.57 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.73.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.40.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.40.0)
Requirement already satisfied: opentelemetry-proto==1.40.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.40.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.61b0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk>=1.2.0->chromadb) (0.61b0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings>=2.0->chromadb) (1.2.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb) (2.19.2)
Requirement already satisfied: huggingface-hub<2.0,>=0.16.4 in /usr/local/lib/python3.12/dist-packages (from tokenizers>=0.13.2->chromadb) (1.6.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (0.0.4)
Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.7.1)
Requirement already satisfied: uvloop>=0.15.1 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.22.1)
Requirement already satisfied: watchfiles>=0.20 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (1.1.1)
Requirement already satisfied: websockets>=10.4 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (15.0.1)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (1.4.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api>=1.2.0->chromadb) (3.23.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->chromadb) (0.1.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kubernetes>=28.1.0->chromadb) (3.4.5)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib->kubernetes>=28.1.0->chromadb) (3.3.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy->onnxruntime>=1.14.1->chromadb) (1.3.0)

In [12]:
!pip install langchain-chroma

Requirement already satisfied: langchain-chroma in /usr/local/lib/python3.12/dist-packages (1.1.0)
Requirement already satisfied: chromadb<2.0.0,>=1.3.5 in /usr/local/lib/python3.12/dist-packages (from langchain-chroma) (1.5.5)
Requirement already satisfied: langchain-core<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from langchain-chroma) (1.2.19)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from langchain-chroma) (2.0.2)
Requirement already satisfied: build>=1.0.3 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.4.0)
Requirement already satisfied: pydantic>=2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (2.12.3)
Requirement already satisfied: pydantic-settings>=2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (2.13.1)
Requirement already satisfied: pybase64>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.4.3)
Requirement already satisfied: uvicorn>=0.18.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.41.0)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (4.15.0)
Requirement already satisfied: onnxruntime>=1.14.1 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.24.4)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.40.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.40.0)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.40.0)
Requirement already satisfied: tokenizers>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.22.2)
Requirement already satisfied: pypika>=0.48.9 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.51.1)
Requirement already satisfied: tqdm>=4.65.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (4.67.3)
Requirement already satisfied: overrides>=7.3.1 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (7.7.0)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (6.5.2)
Requirement already satisfied: grpcio>=1.58.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.78.0)
Requirement already satisfied: bcrypt>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (5.0.0)
Requirement already satisfied: typer>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.24.1)
Requirement already satisfied: kubernetes>=28.1.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (35.0.0)
Requirement already satisfied: tenacity>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (9.1.4)
Requirement already satisfied: pyyaml>=6.0.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (6.0.3)
Requirement already satisfied: mmh3>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (5.2.1)
Requirement already satisfied: orjson>=3.9.12 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (3.11.7)
Requirement already satisfied: httpx>=0.27.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.28.1)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (13.9.4)
Requirement already satisfied: jsonschema>=4.19.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (4.26.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.1.3->langchain-chroma) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.1.3->langchain-chroma) (0.7.16)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.1.3->langchain-chroma) (26.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.1.3->langchain-chroma) (0.14.1)
Requirement already satisfied: pyproject_hooks in /usr/local/lib/python3.12/dist-packages (from build>=1.0.3->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.2.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.27.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.1.3->langchain-chroma) (3.0.0)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.30.0)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.17.0)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (2.9.0.post0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.9.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (2.32.5)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (2.0.0)
Requirement already satisfied: urllib3!=2.6.0,>=1.24.2 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (2.5.0)
Requirement already satisfied: durationpy>=0.7 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.10)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.1.3->langchain-chroma) (1.0.0)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.1.3->langchain-chroma) (3.6.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.1.3->langchain-chroma) (0.25.0)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb<2.0.0,>=1.3.5->langchain-chroma) (25.12.19)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb<2.0.0,>=1.3.5->langchain-chroma) (5.29.6)
Requirement already satisfied: sympy in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.14.0)
Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-api>=1.2.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (8.7.1)
Requirement already satisfied: googleapis-common-protos~=1.57 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.73.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.40.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.40.0)
Requirement already satisfied: opentelemetry-proto==1.40.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.40.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.61b0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk>=1.2.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.61b0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings>=2.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.2.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (2.19.2)
Requirement already satisfied: huggingface-hub<2.0,>=0.16.4 in /usr/local/lib/python3.12/dist-packages (from tokenizers>=0.13.2->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.6.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.0.4)
Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.7.1)
Requirement already satisfied: uvloop>=0.15.1 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.22.1)
Requirement already satisfied: watchfiles>=0.20 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.1.1)
Requirement already satisfied: websockets>=10.4 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb<2.0.0,>=1.3.5->langchain-chroma) (15.0.1)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb<2.0.0,>=1.3.5->langchain-chroma) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb<2.0.0,>=1.3.5->langchain-chroma) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.4.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api>=1.2.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (3.23.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.1.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (3.4.5)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib->kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (3.3.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy->onnxruntime>=1.14.1->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.3.0)

In [13]:
from langchain_chroma import Chroma

In [14]:
from langchain_community.document_loaders import PyPDFLoader

In [15]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

In [16]:
!pip install --upgrade opentelemetry-api
!pip install --upgrade opentelemetry-sdk

Requirement already satisfied: opentelemetry-api in /usr/local/lib/python3.12/dist-packages (1.40.0)
Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-api) (8.7.1)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-api) (4.15.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api) (3.23.0)
Requirement already satisfied: opentelemetry-sdk in /usr/local/lib/python3.12/dist-packages (1.40.0)
Requirement already satisfied: opentelemetry-api==1.40.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk) (1.40.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.61b0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk) (0.61b0)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk) (4.15.0)
Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-api==1.40.0->opentelemetry-sdk) (8.7.1)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api==1.40.0->opentelemetry-sdk) (3.23.0)

## Text Splitting

In [17]:
# 위에서 사용했던 코드입니다
loader = PyPDFLoader("/content/drive/MyDrive/Demian.pdf")
pages = loader.load_and_split()

text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=50, length_function = tiktoken_len)
texts = text_splitter.split_documents(pages)

In [18]:
tiktoken_length = []
for doc in texts:
    # chunk(Document 객체)가 아니라 내부의 텍스트(.page_content)를 전달
    tiktoken_length.append(tiktoken_len(doc.page_content))

print(f"생성된 조각 개수: {len(texts)}")
print(f"조각별 토큰 길이: {tiktoken_length}")

생성된 조각 개수: 182
조각별 토큰 길이: [16, 36, 327, 426, 303, 414, 416, 427, 418, 405, 388, 399, 423, 409, 411, 396, 452, 425, 433, 432, 431, 423, 425, 387, 427, 283, 318, 418, 399, 425, 419, 440, 399, 403, 421, 407, 395, 388, 399, 400, 400, 397, 417, 359, 400, 400, 406, 448, 282, 301, 414, 422, 442, 421, 411, 415, 414, 396, 427, 440, 414, 362, 418, 439, 437, 389, 422, 383, 393, 411, 417, 332, 313, 422, 402, 432, 415, 429, 449, 418, 424, 441, 416, 411, 403, 433, 418, 414, 427, 444, 375, 413, 410, 431, 441, 431, 268, 315, 416, 415, 399, 423, 456, 412, 452, 411, 435, 396, 406, 386, 419, 438, 421, 401, 435, 429, 395, 323, 432, 423, 442, 386, 396, 416, 391, 426, 427, 414, 419, 401, 355, 424, 397, 385, 389, 424, 418, 421, 447, 422, 421, 153, 312, 421, 391, 402, 376, 407, 400, 398, 423, 428, 415, 411, 401, 410, 401, 424, 402, 387, 409, 387, 429, 419, 411, 403, 420, 403, 339, 383, 293, 326, 421, 365, 389, 400, 378, 405, 431, 408, 407, 230]

### 텍스트 임베딩

In [19]:
import openai

In [20]:
client = openai.OpenAI()

In [21]:
for model in client.models.list():
    if "embedding" in model.id:
        print(model.id)

text-embedding-3-small
text-embedding-3-large
text-embedding-ada-002

In [22]:
from langchain_openai import OpenAIEmbeddings

## 벡터 데이터베이스(Vector DB) 구축

In [23]:
embedding_model = OpenAIEmbeddings(model="text-embedding-3-small")

In [24]:
db = Chroma.from_documents(texts, embedding_model)

In [25]:
query = "how Demian look like?"
docs = db.similarity_search(query)

In [26]:
print(docs[3].page_content)

DEMIAN
character and have some significance. But I merely knew
that Demian's mother was reported to be very wealthy.
It was also said that neither she nor her son ever
attended church. One boy wondered whether they might
not be Jews but they could equally well be Mohamme­
dans. Tales were also current of Max Demian's physical
prowess. He certainly had greatly humiliated the strong­
est boy in his class who had challenged him to a fight
and called him a coward when he refused to fight. Those
who were present said Demian had just taken him by the
scruff of the neck with one hand and squeezed hard,
whereupon the boy had gone white and crept off. He
was unable to use his arm for days afterwards. The
whole of one evening it was rumoured that he had died.
For a time no assertion was too extravagant to be
believed, everything about him was amazing and excit­
ing. Then they had enough, temporarily at any rate. Not
much later there was further gossip among us; some boys
reported that Demian associated with girls and "knew
everything.'
Meanwhile my business with Franz Kromer followed
its inevitable course. I could not escape him, for even
when he left me in peace for a few days, I was still bound
to him. He haunted my dreams like my own shadow and
any spell that he failed to cast over me in reality my
imagination allowed him to cast in those dreams in
which I became utterly his slave. I lived in them-I was
always a great dreamer-and I used up my health and
strength more in these shadows than in real life. A
recurrent nightmare was that Kromer was torturing me,
spitting and kneeling on me and, what was worse, lead-
86
Downloaded from https://www.holybooks.com

## Reverse HyDE 구현

In [27]:
# [핵심 로직] Reverse HyDE 구현 예시
from langchain_core.documents import Document

# 1. 데이터를 담을 빈 리스트 생성
reverse_hyde_texts = []

# 2. 진행 상황 출력
print(f"총 {len(texts)}개의 문서 조각에서 예상 질문 생성을 시작합니다...")

# 3. 루프 실행
for i, doc in enumerate(texts):
    # 진행 상황 출력
    print(f"[{i+1}/{len(texts)}] 번째 조각 처리 중...")

    # LLM에게 예상 질문 생성 요청 (문구는 필요에 따라 조정 가능)
    # response.content는 LLM이 생성한 답변 텍스트입니다.
    response = llm_openai.invoke(f"다음 내용을 읽고, 이 내용이 정답이 될 수 있는 질문 3개만 써줘:\n\n{doc.page_content}")

    # 원본 내용 + 예상 질문 합치기 (이것이 Reverse HyDE의 핵심입니다)
    enhanced_content = f"예상 질문들:\n{response.content}\n\n원본 내용:\n{doc.page_content}"

    # 새로운 Document 객체 생성 (기존 metadata 유지)
    new_doc = Document(page_content=enhanced_content, metadata=doc.metadata)
    reverse_hyde_texts.append(new_doc)

# 4. 강화된 데이터를 벡터 DB에 저장 (루프가 완전히 끝난 후 실행)
# embedding_model은 이미 정의되어 있다고 가정합니다.
docsearch = Chroma.from_documents(
    documents=reverse_hyde_texts,
    embedding=embedding_model,
    collection_name="reverse_hyde_collection" # 선택 사항: 컬렉션 이름 지정
)

print(f"총 {len(reverse_hyde_texts)}개의 강화된 문서로 Vector Database 구축이 완료되었습니다!")

총 182개의 문서 조각에서 예상 질문 생성을 시작합니다...
[1/182] 번째 조각 처리 중...
[2/182] 번째 조각 처리 중...
[3/182] 번째 조각 처리 중...
[4/182] 번째 조각 처리 중...
[5/182] 번째 조각 처리 중...
[6/182] 번째 조각 처리 중...
[7/182] 번째 조각 처리 중...
[8/182] 번째 조각 처리 중...
[9/182] 번째 조각 처리 중...
[10/182] 번째 조각 처리 중...
[11/182] 번째 조각 처리 중...
[12/182] 번째 조각 처리 중...
[13/182] 번째 조각 처리 중...
[14/182] 번째 조각 처리 중...
[15/182] 번째 조각 처리 중...
[16/182] 번째 조각 처리 중...
[17/182] 번째 조각 처리 중...
[18/182] 번째 조각 처리 중...
[19/182] 번째 조각 처리 중...
[20/182] 번째 조각 처리 중...
[21/182] 번째 조각 처리 중...
[22/182] 번째 조각 처리 중...
[23/182] 번째 조각 처리 중...
[24/182] 번째 조각 처리 중...
[25/182] 번째 조각 처리 중...
[26/182] 번째 조각 처리 중...
[27/182] 번째 조각 처리 중...
[28/182] 번째 조각 처리 중...
[29/182] 번째 조각 처리 중...
[30/182] 번째 조각 처리 중...
[31/182] 번째 조각 처리 중...
[32/182] 번째 조각 처리 중...
[33/182] 번째 조각 처리 중...
[34/182] 번째 조각 처리 중...
[35/182] 번째 조각 처리 중...
[36/182] 번째 조각 처리 중...
[37/182] 번째 조각 처리 중...
[38/182] 번째 조각 처리 중...
[39/182] 번째 조각 처리 중...
[40/182] 번째 조각 처리 중...
[41/182] 번째 조각 처리 중...
[42/182] 번째 조각 처리 중...
[43/182] 번째 조각 처리 중...
[44/182] 번째 조각 처리 중...
[45/182] 번째 조각 처리 중...
[46/182] 번째 조각 처리 중...
[47/182] 번째 조각 처리 중...
[48/182] 번째 조각 처리 중...
[49/182] 번째 조각 처리 중...
[50/182] 번째 조각 처리 중...
[51/182] 번째 조각 처리 중...
[52/182] 번째 조각 처리 중...
[53/182] 번째 조각 처리 중...
[54/182] 번째 조각 처리 중...
[55/182] 번째 조각 처리 중...
[56/182] 번째 조각 처리 중...
[57/182] 번째 조각 처리 중...
[58/182] 번째 조각 처리 중...
[59/182] 번째 조각 처리 중...
[60/182] 번째 조각 처리 중...
[61/182] 번째 조각 처리 중...
[62/182] 번째 조각 처리 중...
[63/182] 번째 조각 처리 중...
[64/182] 번째 조각 처리 중...
[65/182] 번째 조각 처리 중...
[66/182] 번째 조각 처리 중...
[67/182] 번째 조각 처리 중...
[68/182] 번째 조각 처리 중...
[69/182] 번째 조각 처리 중...
[70/182] 번째 조각 처리 중...
[71/182] 번째 조각 처리 중...
[72/182] 번째 조각 처리 중...
[73/182] 번째 조각 처리 중...
[74/182] 번째 조각 처리 중...
[75/182] 번째 조각 처리 중...
[76/182] 번째 조각 처리 중...
[77/182] 번째 조각 처리 중...
[78/182] 번째 조각 처리 중...
[79/182] 번째 조각 처리 중...
[80/182] 번째 조각 처리 중...
[81/182] 번째 조각 처리 중...
[82/182] 번째 조각 처리 중...
[83/182] 번째 조각 처리 중...
[84/182] 번째 조각 처리 중...
[85/182] 번째 조각 처리 중...
[86/182] 번째 조각 처리 중...
[87/182] 번째 조각 처리 중...
[88/182] 번째 조각 처리 중...
[89/182] 번째 조각 처리 중...
[90/182] 번째 조각 처리 중...
[91/182] 번째 조각 처리 중...
[92/182] 번째 조각 처리 중...
[93/182] 번째 조각 처리 중...
[94/182] 번째 조각 처리 중...
[95/182] 번째 조각 처리 중...
[96/182] 번째 조각 처리 중...
[97/182] 번째 조각 처리 중...
[98/182] 번째 조각 처리 중...
[99/182] 번째 조각 처리 중...
[100/182] 번째 조각 처리 중...
[101/182] 번째 조각 처리 중...
[102/182] 번째 조각 처리 중...
[103/182] 번째 조각 처리 중...
[104/182] 번째 조각 처리 중...
[105/182] 번째 조각 처리 중...
[106/182] 번째 조각 처리 중...
[107/182] 번째 조각 처리 중...
[108/182] 번째 조각 처리 중...
[109/182] 번째 조각 처리 중...
[110/182] 번째 조각 처리 중...
[111/182] 번째 조각 처리 중...
[112/182] 번째 조각 처리 중...
[113/182] 번째 조각 처리 중...
[114/182] 번째 조각 처리 중...
[115/182] 번째 조각 처리 중...
[116/182] 번째 조각 처리 중...
[117/182] 번째 조각 처리 중...
[118/182] 번째 조각 처리 중...
[119/182] 번째 조각 처리 중...
[120/182] 번째 조각 처리 중...
[121/182] 번째 조각 처리 중...
[122/182] 번째 조각 처리 중...
[123/182] 번째 조각 처리 중...
[124/182] 번째 조각 처리 중...
[125/182] 번째 조각 처리 중...
[126/182] 번째 조각 처리 중...
[127/182] 번째 조각 처리 중...
[128/182] 번째 조각 처리 중...
[129/182] 번째 조각 처리 중...
[130/182] 번째 조각 처리 중...
[131/182] 번째 조각 처리 중...
[132/182] 번째 조각 처리 중...
[133/182] 번째 조각 처리 중...
[134/182] 번째 조각 처리 중...
[135/182] 번째 조각 처리 중...
[136/182] 번째 조각 처리 중...
[137/182] 번째 조각 처리 중...
[138/182] 번째 조각 처리 중...
[139/182] 번째 조각 처리 중...
[140/182] 번째 조각 처리 중...
[141/182] 번째 조각 처리 중...
[142/182] 번째 조각 처리 중...
[143/182] 번째 조각 처리 중...
[144/182] 번째 조각 처리 중...
[145/182] 번째 조각 처리 중...
[146/182] 번째 조각 처리 중...
[147/182] 번째 조각 처리 중...
[148/182] 번째 조각 처리 중...
[149/182] 번째 조각 처리 중...
[150/182] 번째 조각 처리 중...
[151/182] 번째 조각 처리 중...
[152/182] 번째 조각 처리 중...
[153/182] 번째 조각 처리 중...
[154/182] 번째 조각 처리 중...
[155/182] 번째 조각 처리 중...
[156/182] 번째 조각 처리 중...
[157/182] 번째 조각 처리 중...
[158/182] 번째 조각 처리 중...
[159/182] 번째 조각 처리 중...
[160/182] 번째 조각 처리 중...
[161/182] 번째 조각 처리 중...
[162/182] 번째 조각 처리 중...
[163/182] 번째 조각 처리 중...
[164/182] 번째 조각 처리 중...
[165/182] 번째 조각 처리 중...
[166/182] 번째 조각 처리 중...
[167/182] 번째 조각 처리 중...
[168/182] 번째 조각 처리 중...
[169/182] 번째 조각 처리 중...
[170/182] 번째 조각 처리 중...
[171/182] 번째 조각 처리 중...
[172/182] 번째 조각 처리 중...
[173/182] 번째 조각 처리 중...
[174/182] 번째 조각 처리 중...
[175/182] 번째 조각 처리 중...
[176/182] 번째 조각 처리 중...
[177/182] 번째 조각 처리 중...
[178/182] 번째 조각 처리 중...
[179/182] 번째 조각 처리 중...
[180/182] 번째 조각 처리 중...
[181/182] 번째 조각 처리 중...
[182/182] 번째 조각 처리 중...
총 182개의 강화된 문서로 Vector Database 구축이 완료되었습니다!

## Retrieval

In [28]:
!pip install -U langchain langchain-classic

Requirement already satisfied: langchain in /usr/local/lib/python3.12/dist-packages (1.2.12)
Requirement already satisfied: langchain-classic in /usr/local/lib/python3.12/dist-packages (1.0.3)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.10 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.2.19)
Requirement already satisfied: langgraph<1.2.0,>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.1.1)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain) (2.12.3)
Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from langchain-classic) (1.1.1)
Requirement already satisfied: langsmith<1.0.0,>=0.1.17 in /usr/local/lib/python3.12/dist-packages (from langchain-classic) (0.7.16)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-classic) (6.0.3)
Requirement already satisfied: requests<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from langchain-classic) (2.32.5)
Requirement already satisfied: sqlalchemy<3.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-classic) (2.0.48)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (1.33)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (26.0)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (0.14.1)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.2.0,>=1.1.1->langchain) (4.0.1)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.8 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.2.0,>=1.1.1->langchain) (1.0.8)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.2.0,>=1.1.1->langchain) (0.3.11)
Requirement already satisfied: xxhash>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.2.0,>=1.1.1->langchain) (3.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.17->langchain-classic) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.17->langchain-classic) (3.11.7)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.17->langchain-classic) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.17->langchain-classic) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->langchain-classic) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->langchain-classic) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->langchain-classic) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->langchain-classic) (2026.2.25)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<3.0.0,>=1.4.0->langchain-classic) (3.3.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.17->langchain-classic) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.17->langchain-classic) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.17->langchain-classic) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.10->langchain) (3.0.0)
Requirement already satisfied: ormsgpack>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from langgraph-checkpoint<5.0.0,>=2.1.0->langgraph<1.2.0,>=1.1.1->langchain) (1.12.2)

In [29]:
# from langchain.chains import RetrievalQA에서 바꾼 것
from langchain_classic.chains.retrieval_qa.base import RetrievalQA

In [30]:
from langchain_core.callbacks.streaming_stdout import StreamingStdOutCallbackHandler

llm = ChatOpenAI(
    model="gpt-4o",
    temperature=0.0,
    streaming=True,
    callbacks=[StreamingStdOutCallbackHandler()]
)

In [31]:
qa = RetrievalQA.from_chain_type(
    llm,
    chain_type="stuff",
    retriever=docsearch.as_retriever(
      search_type="mmr",
      search_kwargs={"k": 3, "fetch_k" : 10}),
    return_source_documents=True)

In [32]:
# 10. 질문 실행 및 결과 출력
query = "Who is Sinclair?"
result = qa.invoke(query)

from IPython.display import Markdown, display
display(Markdown(result["result"]))

I don't know.

I don't know.

#### RAG를 사용하지 않은 llm 호출

In [33]:
# llm2 = ChatOpenAI(
#     model="gpt-4o-mini")
# request = llm2.invoke("how demian looks like")
# display(Markdown(request.content))

## RAGAS

In [34]:
!pip install ragas datasets

Requirement already satisfied: ragas in /usr/local/lib/python3.12/dist-packages (0.4.3)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: numpy<3.0.0,>=1.21.0 in /usr/local/lib/python3.12/dist-packages (from ragas) (2.0.2)
Requirement already satisfied: tiktoken in /usr/local/lib/python3.12/dist-packages (from ragas) (0.12.0)
Requirement already satisfied: pydantic>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ragas) (2.12.3)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from ragas) (1.6.0)
Requirement already satisfied: appdirs in /usr/local/lib/python3.12/dist-packages (from ragas) (1.4.4)
Requirement already satisfied: diskcache>=5.6.3 in /usr/local/lib/python3.12/dist-packages (from ragas) (5.6.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from ragas) (0.24.1)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from ragas) (13.9.4)
Requirement already satisfied: openai>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ragas) (2.26.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from ragas) (4.67.3)
Requirement already satisfied: instructor in /usr/local/lib/python3.12/dist-packages (from ragas) (1.14.5)
Requirement already satisfied: pillow>=10.4.0 in /usr/local/lib/python3.12/dist-packages (from ragas) (11.3.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from ragas) (3.6.1)
Requirement already satisfied: scikit-network in /usr/local/lib/python3.12/dist-packages (from ragas) (0.33.5)
Requirement already satisfied: langchain in /usr/local/lib/python3.12/dist-packages (from ragas) (1.2.12)
Requirement already satisfied: langchain-core in /usr/local/lib/python3.12/dist-packages (from ragas) (1.2.19)
Requirement already satisfied: langchain-community in /usr/local/lib/python3.12/dist-packages (from ragas) (0.4.1)
Requirement already satisfied: langchain_openai in /usr/local/lib/python3.12/dist-packages (from ragas) (1.1.11)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.25.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.5)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (1.6.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.13.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (1.4.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.15.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai>=1.0.0->ragas) (4.12.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai>=1.0.0->ragas) (1.9.0)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai>=1.0.0->ragas) (0.11.1)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai>=1.0.0->ragas) (1.3.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->ragas) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->ragas) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->ragas) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.2.25)
Requirement already satisfied: docstring-parser<1.0,>=0.16 in /usr/local/lib/python3.12/dist-packages (from instructor->ragas) (0.17.0)
Requirement already satisfied: jinja2<4.0.0,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from instructor->ragas) (3.1.6)
Requirement already satisfied: tenacity<10.0.0,>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from instructor->ragas) (9.1.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->ragas) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->ragas) (2.19.2)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->ragas) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->ragas) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->ragas) (0.0.4)
Requirement already satisfied: langgraph<1.2.0,>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from langchain->ragas) (1.1.1)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core->ragas) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core->ragas) (0.7.16)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core->ragas) (0.14.1)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community->ragas) (1.0.3)
Requirement already satisfied: SQLAlchemy<3.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community->ragas) (2.0.48)
Requirement already satisfied: dataclasses-json<0.7.0,>=0.6.7 in /usr/local/lib/python3.12/dist-packages (from langchain-community->ragas) (0.6.7)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from langchain-community->ragas) (2.13.1)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community->ragas) (0.4.3)
Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.12/dist-packages (from tiktoken->ragas) (2025.11.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: scipy>=1.7.3 in /usr/local/lib/python3.12/dist-packages (from scikit-network->ragas) (1.16.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community->ragas) (3.26.2)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community->ragas) (0.9.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2<4.0.0,>=3.1.4->instructor->ragas) (3.0.3)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core->ragas) (3.0.0)
Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from langchain-classic<2.0.0,>=1.0.0->langchain-community->ragas) (1.1.1)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.2.0,>=1.1.1->langchain->ragas) (4.0.1)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.8 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.2.0,>=1.1.1->langchain->ragas) (1.0.8)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.2.0,>=1.1.1->langchain->ragas) (0.3.11)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core->ragas) (3.11.7)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core->ragas) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core->ragas) (0.25.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->ragas) (0.1.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community->ragas) (1.2.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from SQLAlchemy<3.0.0,>=1.4.0->langchain-community->ragas) (3.3.2)
Requirement already satisfied: ormsgpack>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from langgraph-checkpoint<5.0.0,>=2.1.0->langgraph<1.2.0,>=1.1.1->langchain->ragas) (1.12.2)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7.0,>=0.6.7->langchain-community->ragas) (1.1.0)

In [35]:
from datasets import Dataset
from ragas import evaluate
from ragas.metrics import (
    faithfulness,
    answer_relevancy,
    context_recall,
    context_precision,
)
import pandas as pd

/usr/local/lib/python3.12/dist-packages/google/colab/_import_hooks/_hook_injector.py:55: FutureWarning:

All support for the `google.generativeai` package has ended. It will no longer be receiving
updates or bug fixes. Please switch to the `google.genai` package as soon as possible.
See README for more details:

https://github.com/google-gemini/deprecated-generative-ai-python/blob/main/README.md

  loader.exec_module(module)
/tmp/ipykernel_27532/2706617862.py:3: DeprecationWarning: Importing faithfulness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import faithfulness
  from ragas.metrics import (
/tmp/ipykernel_27532/2706617862.py:3: DeprecationWarning: Importing answer_relevancy from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import answer_relevancy
  from ragas.metrics import (
/tmp/ipykernel_27532/2706617862.py:3: DeprecationWarning: Importing context_recall from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import context_recall
  from ragas.metrics import (
/tmp/ipykernel_27532/2706617862.py:3: DeprecationWarning: Importing context_precision from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import context_precision
  from ragas.metrics import (

In [36]:
# 1. 평가용 질문 및 정답 정의
eval_questions = [
    "싱클레어는 누구니?",
    "데미안이 싱클레어에게 카인과 아벨에 대해 설명한 내용은 무엇인가요?",
    "크로머는 어떤 방식으로 싱클레어를 협박했나요?"
]

ground_truths = [
    "싱클레어는 소설 '데미안'의 주인공으로, 밝은 세계와 어두운 세계 사이에서 방황하며 자아를 찾아가는 인물입니다.",
    "데미안은 카인의 표식이 악의 상징이 아니라, 남들보다 강하고 지적인 사람들을 구별해주는 고귀한 표식이라고 설명했습니다.",
    "크로머는 싱클레어가 이웃집 과수원에서 사과를 훔쳤다는 거짓 고백을 약점 잡아 돈을 요구하며 그를 괴롭혔습니다."
]

In [37]:
# 2. 결과 수집
results = []
for query in eval_questions:
    # QA 시스템 호출
    response = qa.invoke(query)

    # 답변 추출 (RetrievalQA 결과 구조에 따라 수정)
    answer = response.get("result") or response.get("answer")

    # 검색된 근거 추출 (위에서 만든 docsearch 활용)
    retrieved_docs = docsearch.as_retriever().invoke(query)
    context_list = [doc.page_content for doc in retrieved_docs]

    results.append({
        "question": query,
        "answer": answer,
        "contexts": context_list
    })

저는 싱클레어에 대한 정보를 가지고 있지 않습니다.그 내용에 대한 정보는 제공되지 않았습니다. 제가 알고 있는 한, 데미안이 싱클레어에게 카인과 아벨에 대해 설명한 구체적인 내용은 없습니다.그에 대한 정보는 제공되지 않았습니다.

In [38]:
# 3. 데이터셋 변환
data = {
    "question": [r["question"] for r in results],
    "answer": [r["answer"] for r in results],
    "contexts": [r["contexts"] for r in results],
    "ground_truth": ground_truths
}
dataset = Dataset.from_dict(data)

In [39]:
# 4. Ragas 평가 실행 (OpenAI API 키가 설정되어 있어야 합니다)
print("Ragas 평가를 시작합니다...")
result = evaluate(
    dataset=dataset,
    metrics=[
        context_precision,
        context_recall,
        faithfulness,
        answer_relevancy,
    ],
)

Ragas 평가를 시작합니다...

Evaluating:   0%|          | 0/12 [00:00<?, ?it/s]

WARNING:ragas.prompt.pydantic_prompt:LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
ERROR:ragas.executor:Exception raised in Job[3]: AttributeError('OpenAIEmbeddings' object has no attribute 'embed_query')
WARNING:ragas.prompt.pydantic_prompt:LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
ERROR:ragas.executor:Exception raised in Job[7]: AttributeError('OpenAIEmbeddings' object has no attribute 'embed_query')
WARNING:ragas.prompt.pydantic_prompt:LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
ERROR:ragas.executor:Exception raised in Job[11]: AttributeError('OpenAIEmbeddings' object has no attribute 'embed_query')

In [ ]:
# 5. 결과 확인
print("\n[Ragas 평가 결과]")
print(result)
df = result.to_pandas()
display(df)

[Ragas 평가 결과]
{'context_precision': 0.6019, 'context_recall': 1.0000, 'faithfulness': 0.3333, 'answer_relevancy': nan}

,user_input,retrieved_contexts,response,reference,context_precision,context_recall,faithfulness,answer_relevancy
0,싱클레어는 누구니?,"[예상 질문들:\n1. ""이 글에서 언급된 'Abraxas'는 어떤 의미를 가지고 ...",저는 싱클레어에 대한 정보를 가지고 있지 않습니다.,"싱클레어는 소설 '데미안'의 주인공으로, 밝은 세계와 어두운 세계 사이에서 방황하며...",0.000000,1.0,0.0,NaN
1,데미안이 싱클레어에게 카인과 아벨에 대해 설명한 내용은 무엇인가요?,[예상 질문들:\n1. 왜 많은 사람들이 카인을 아벨보다 더 나은 인물로 간주한다고...,"그 내용에 대한 정보는 제공되지 않았습니다. 제가 알고 있는 한, 데미안이 싱클레어...","데미안은 카인의 표식이 악의 상징이 아니라, 남들보다 강하고 지적인 사람들을 구별해...",0.805556,1.0,0.0,NaN
2,크로머는 어떤 방식으로 싱클레어를 협박했나요?,[예상 질문들:\n1. 주인공은 왜 자신의 시계를 크로머에게 주려고 했나요?\n2....,그에 대한 정보는 제공되지 않았습니다.,크로머는 싱클레어가 이웃집 과수원에서 사과를 훔쳤다는 거짓 고백을 약점 잡아 돈을 ...,1.000000,1.0,1.0,NaN

## 정성 평가

In [40]:
# 1. 분석할 질문 리스트 (평가에 사용했던 질문과 동일하게 설정)
analysis_questions = [
    "싱클레어는 누구니?",
    "데미안이 싱클레어에게 카인과 아벨에 대해 설명한 내용은 무엇인가요?",
    "크로머는 어떤 방식으로 싱클레어를 협박했나요?"
]

print("=== Retrieval Analysis (검색 결과 적절성 검토) ===\n")

analysis_results = []

for i, query in enumerate(analysis_questions):
    print(f"🔎 질문 {i+1}: {query}")

    # docsearch(Chroma DB)에서 관련 문서 검색 (k=3)
    # Reverse HyDE로 구축된 DB이므로 '예상 질문'이 포함된 문서를 가져옵니다.
    retrieved_docs = docsearch.as_retriever(search_kwargs={"k": 3}).invoke(query)

    print(f"✅ 검색된 문서 개수: {len(retrieved_docs)}")

    for j, doc in enumerate(retrieved_docs):
        # 검색된 내용의 앞부분 200자만 추출하여 출력
        content_preview = doc.page_content.replace('\n', ' ')[:200]
        source = doc.metadata.get('source', '알 수 없음')
        page = doc.metadata.get('page', '-')

        print(f"   [문서 {j+1}] (출처: {source}, {page}페이지)")
        print(f"   내용 요약: {content_preview}...")
        print("-" * 50)

    print("\n" + "="*80 + "\n")

# (선택 사항) 결과를 표 형태로 정리해서 보고 싶을 때
analysis_data = []
for query in analysis_questions:
    docs = docsearch.as_retriever(search_kwargs={"k": 3}).invoke(query)
    analysis_data.append({
        "Question": query,
        "Top_1_Context": docs[0].page_content[:300] if docs else "검색 결과 없음",
        "Top_2_Context": docs[1].page_content[:300] if len(docs) > 1 else "-",
        "Top_3_Context": docs[2].page_content[:300] if len(docs) > 2 else "-"
    })

df_analysis = pd.DataFrame(analysis_data)
display(df_analysis)

=== Retrieval Analysis (검색 결과 적절성 검토) ===

🔎 질문 1: 싱클레어는 누구니?
✅ 검색된 문서 개수: 3
   [문서 1] (출처: /content/drive/MyDrive/Demian.pdf, 118페이지)
   내용 요약: 예상 질문들: 1. "이 글에서 언급된 'Abraxas'는 어떤 의미를 가지고 있으며, 그가 상징하는 것은 무엇인가요?" 2. "주인공이 꿈에서 경험하는 감정과 그 꿈의 내용은 무엇을 나타내고 있나요?" 3. "주인공이 '자신을 오스트리치로 만들라'는 조언을 통해 배우고자 하는 교훈은 무엇인가요?"  원본 내용: JACOB AND THE ANGEL  try...
--------------------------------------------------
   [문서 2] (출처: /content/drive/MyDrive/Demian.pdf, 13페이지)
   내용 요약: 예상 질문들: 1. 주인공은 왜 자신의 시계를 크로머에게 주려고 했나요? 2. 크로머는 주인공의 시계에 대해 어떤 반응을 보였나요? 3. 주인공은 크로머가 떠나지 않도록 어떤 감정을 표현했나요?  원본 내용: DEMIAN  Then I remembered my watch. It was a silver watch but  it did not go. I jus...
--------------------------------------------------
   [문서 3] (출처: /content/drive/MyDrive/Demian.pdf, 88페이지)
   내용 요약: 예상 질문들: 1. 이 그림이 비아트리스의 삶에 어떤 영향을 미쳤나요? 2. 비아트리스는 왜 이 그림을 숨겨두었고, 나중에 다시 꺼내게 되었나요? 3. 비아트리스가 꿈에서 경험한 새로운 그림은 어떤 모습이었고, 그 그림이 그녀에게 어떤 감정을 불러일으켰나요?  원본 내용: BEATRICE  This picture haunted my thoughts for ...
--------------------------------------------------

================================================================================

🔎 질문 2: 데미안이 싱클레어에게 카인과 아벨에 대해 설명한 내용은 무엇인가요?
✅ 검색된 문서 개수: 3
   [문서 1] (출처: /content/drive/MyDrive/Demian.pdf, 48페이지)
   내용 요약: 예상 질문들: 1. 왜 많은 사람들이 카인을 아벨보다 더 나은 인물로 간주한다고 생각했는가? 2. 카인과 아벨에 대한 해석이 구약 시대부터 존재했음을 아버지가 어떻게 설명했는가? 3. 아버지가 카인에 대한 긍정적인 해석을 경계한 이유는 무엇인가?  원본 내용: CAIN  how well I realise that today. Nothing in the we...
--------------------------------------------------
   [문서 2] (출처: /content/drive/MyDrive/Demian.pdf, 65페이지)
   내용 요약: 예상 질문들: 1. 데미안이 말한 "신과 악"에 대한 관점은 주인공에게 어떤 영향을 미쳤나요? 2. 주인공이 느낀 두 세계의 개념은 그의 개인적인 삶에 어떤 의미를 가졌나요? 3. 데미안과의 대화에서 주인공이 느낀 책임감과 자립의 감정은 무엇을 암시하나요?  원본 내용: DEMIAN  braces the Devil in himself and before w...
--------------------------------------------------
   [문서 3] (출처: /content/drive/MyDrive/Demian.pdf, 29페이지)
   내용 요약: 예상 질문들: 1. 어떻게 카인의 이야기를 다른 시각에서 해석할 수 있다고 주장하나요? 2. 카인에게 주어진 '표시'는 실제로 어떤 의미를 가질 수 있다고 설명하나요? 3. 카인의 자녀들이 두려움을 불러일으킨 이유는 무엇이라고 설명하나요?  원본 내용: DEMIAN  "'Yes. I believe, then," he continued, "'that this...
--------------------------------------------------

================================================================================

🔎 질문 3: 크로머는 어떤 방식으로 싱클레어를 협박했나요?
✅ 검색된 문서 개수: 3
   [문서 1] (출처: /content/drive/MyDrive/Demian.pdf, 13페이지)
   내용 요약: 예상 질문들: 1. 주인공은 왜 자신의 시계를 크로머에게 주려고 했나요? 2. 크로머는 주인공의 시계에 대해 어떤 반응을 보였나요? 3. 주인공은 크로머가 떠나지 않도록 어떤 감정을 표현했나요?  원본 내용: DEMIAN  Then I remembered my watch. It was a silver watch but  it did not go. I jus...
--------------------------------------------------
   [문서 2] (출처: /content/drive/MyDrive/Demian.pdf, 107페이지)
   내용 요약: 예상 질문들: 1. 이 인물의 외모에 대한 묘사는 어떤 특징들을 포함하고 있나요? 2. 대화 중 등장인물은 서로에게 어떤 감정을 가지고 있나요? 3. 주인공은 왜 상대방에게 특별한 무언가를 발견하고 싶어하나요?  원본 내용: DEMIAN  I had anticipated. It wu ugly and somewhat wild  looking, interrog...
--------------------------------------------------
   [문서 3] (출처: /content/drive/MyDrive/Demian.pdf, 58페이지)
   내용 요약: 예상 질문들: 1. 어떤 방식으로 수컷 나방이 암컷 나방을 찾는가? 2. 왜 수컷 나방이 암컷 나방보다 더 많은 후각 능력을 갖게 되었는가? 3. 화자의 과거와 관련된 Kromer와의 관계는 어떻게 변화했는가?  원본 내용: THE THIEF  the male fertilizes the female who lays the eggs. H you  get ho...
--------------------------------------------------

================================================================================

,Question,Top_1_Context,Top_2_Context,Top_3_Context
0,싱클레어는 누구니?,"예상 질문들:\n1. ""이 글에서 언급된 'Abraxas'는 어떤 의미를 가지고 있...",예상 질문들:\n1. 주인공은 왜 자신의 시계를 크로머에게 주려고 했나요?\n2. ...,예상 질문들:\n1. 이 그림이 비아트리스의 삶에 어떤 영향을 미쳤나요?\n2. 비...
1,데미안이 싱클레어에게 카인과 아벨에 대해 설명한 내용은 무엇인가요?,예상 질문들:\n1. 왜 많은 사람들이 카인을 아벨보다 더 나은 인물로 간주한다고 ...,"예상 질문들:\n1. 데미안이 말한 ""신과 악""에 대한 관점은 주인공에게 어떤 영향...",예상 질문들:\n1. 어떻게 카인의 이야기를 다른 시각에서 해석할 수 있다고 주장하...
2,크로머는 어떤 방식으로 싱클레어를 협박했나요?,예상 질문들:\n1. 주인공은 왜 자신의 시계를 크로머에게 주려고 했나요?\n2. ...,예상 질문들:\n1. 이 인물의 외모에 대한 묘사는 어떤 특징들을 포함하고 있나요?...,예상 질문들:\n1. 어떤 방식으로 수컷 나방이 암컷 나방을 찾는가?\n2. 왜 수...

▶ 위 정성 평가를 보고 우리가 판단해야 하는 것은, <br>
"내가 던진 질문에 대답할 수 있는 진짜 정보(원본 내용)가 검색된 문서들 안에 포함되어 있는가?"이다. <br>

① 원본 내용(Original Content)에 정답이 있는가? <br>
질문과 관련된 내용이 원본 내용에 들어가있는지 눈으로 확인한다.

② 예상 질문(Generated Questions)이 길잡이 역할을 하는가? <br>
Reverse HyDE로 생성된 질문들이 내가 던진 질문과 맥락이 닿아 있는지 본다.

③ 검색 결과의 중복성 (Diversity) <br>
가져온 원본 내용들이 중복된, 같은 문서는 아닌지 확인한다.

### 지표 해석
Context Recall : 1.0

→ 모든 질문에서 1.0(100%)이 나왔다. 즉, Reverse HyDE를 통해 구축한 DB가 질문에 필요한 정답 데이터를 정확하게 찾아오고 있다는 뜻이다.

Context Precision : 0, 0.8, 1.0

→ 2개의 질문에 대한 평가는 높은 편이다. 질문과 밀접한 관련이 있는 문서들이 최상위권으로 검색되고 있다는 뜻이다.

Faithfulness : 0, 1

→ 0점이 2개다. 문서에는 정답이 있는데, 모델이 "모르겠습니다"라고 답했기 때문에 문서 내용을 전혀 활용하지 못했다고 판단.<br>